-- ════════════════════════════════════════════════════════════════════════════
-- 02_schema_sync_to_live.sql
-- Kisi bhi live Supabase DB (jo SAME codebase se deploy hai) ko bina data-loss
-- current live schema state tak le jane ke liye — SAFE + IDEMPOTENT.
--
-- KAHAAN CHALAYEIN:
--   1. backup lo: Supabase Dashboard -> Database -> Backups (PITR) ya
--      SQL Editor me pehle verification queries chalao.
--   2. Supabase Dashboard -> SQL Editor -> is pura file paste -> RUN.
--   3. SCRIPT HAMESHA SAFE HAI: har create ke pehle drop/IF NOT EXISTS guards;
--      data ko delete/truncate NAHI karta. Baar baar run karna bhi safe hai.
--
-- NOT (important):
--   • backups/supabase/baseline_schema.sql SIRF EMPTY/FRESH DB ke liye hai —
--     live DB par usse NA chalao (pg_dump restore-file hai; partial run par
--     duplicate DDL errors + inconsistent policy state).
--   • Locations tables (20260817) / portal / hardening / geofence etc. abhi
--     nahi include kiye — wo poorane 20-Aug baseline me already the. Agar
--     target DB me locations/product_locations EXISTS NAHI hain, to pehle
--     20260817_product_level_location.sql + 20260820_location_hierarchy.sql
--     alag se chalao.
--   • 20260815 dedupe step duplicate mechanic→user links ko NULL karta hai
--     (live ke 1:1 fix jaisa hi) — intended data-correction, loss nahi.
--   • providers note: data-affecting statements sirf backfill/insert-on-
--     conflict + saaf idempotent guards ke saath hain.
-- ============================================================================


-- ════════════════════════════════════════════════════════════════════════════
-- >>>  20260816_inventory_purchase_orders.sql
-- ════════════════════════════════════════════════════════════════════════════
-- ============================================================================
-- 20260816_inventory_purchase_orders.sql
-- Inventory "krantikari" phase ke liye 2 naye table sets:
--
--   1) Purchase Order workflow
--        - purchase_orders       : ek PO header (supplier, status, total, dates)
--        - purchase_order_items  : PO ke andar products (qty ordered/received)
--      Status flow: pending -> ordered -> received (cancel bhi allowed).
--      Jab PO "received" mark ho to inventory_list me stock-in entries banti hain
--      (frontend isse handle karega; is file me sirf schema hai).
--
--   2) PWA push notification subscriptions
--        - push_subscriptions    : har user ke browser push subscription ki keys
--      In-app low-stock alerts pehle se hain (AIAlertsWidget); ye table PWA
--      web-push deliver karne ke liye subscription store karta hai.
--
-- Style: project ke existing tables jaisa (bigint identity, date_created/
-- date_updated default now(), RLS + "Allow authenticated access" policy).
-- Idempotent: baar baar run karne se error nahi aayega.
--
-- Apply: Supabase SQL Editor me run karo (ek baar).
-- ============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- 1) PURCHASE ORDERS
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.purchase_orders (
  id             bigint generated by default as identity primary key,
  po_code        text not null unique,
  supplier_id    bigint,
  status         text not null default 'pending'
                 check (status in ('pending', 'ordered', 'received', 'cancelled')),
  expected_date  date,
  notes          text default '',
  total_amount   numeric(12,2) not null default 0,
  received_date  date,
  date_created   timestamp with time zone default now() not null,
  date_updated   timestamp with time zone default now() not null
);

alter table public.purchase_orders
  drop constraint if exists purchase_orders_supplier_fk;
alter table public.purchase_orders
  add constraint purchase_orders_supplier_fk
  foreign key (supplier_id) references public.suppliers (id)
  on delete set null;

create index if not exists purchase_orders_status_idx
  on public.purchase_orders (status);
create index if not exists purchase_orders_supplier_idx
  on public.purchase_orders (supplier_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2) PURCHASE ORDER ITEMS
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.purchase_order_items (
  id                 bigint generated by default as identity primary key,
  purchase_order_id  bigint not null,
  product_id         bigint not null,
  qty_ordered        integer not null default 0,
  qty_received       integer not null default 0,
  unit_cost          numeric(12,2) not null default 0,
  date_created       timestamp with time zone default now() not null
);

alter table public.purchase_order_items
  drop constraint if exists purchase_order_items_po_fk;
alter table public.purchase_order_items
  add constraint purchase_order_items_po_fk
  foreign key (purchase_order_id) references public.purchase_orders (id)
  on delete cascade;

alter table public.purchase_order_items
  drop constraint if exists purchase_order_items_product_fk;
alter table public.purchase_order_items
  add constraint purchase_order_items_product_fk
  foreign key (product_id) references public.product_list (id)
  on delete restrict;

create index if not exists purchase_order_items_po_idx
  on public.purchase_order_items (purchase_order_id);
create index if not exists purchase_order_items_product_idx
  on public.purchase_order_items (product_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3) PWA PUSH SUBSCRIPTIONS
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.push_subscriptions (
  id             bigint generated by default as identity primary key,
  user_id        uuid,
  endpoint       text not null unique,
  p256dh         text not null default '',
  auth           text not null default '',
  device_name    text default '',
  enabled        boolean not null default true,
  date_created   timestamp with time zone default now() not null,
  date_updated   timestamp with time zone default now() not null
);

alter table public.push_subscriptions
  drop constraint if exists push_subscriptions_user_fk;
alter table public.push_subscriptions
  add constraint push_subscriptions_user_fk
  foreign key (user_id) references public.profiles (id)
  on delete cascade;

create index if not exists push_subscriptions_user_idx
  on public.push_subscriptions (user_id);
create index if not exists push_subscriptions_enabled_idx
  on public.push_subscriptions (enabled);

-- ─────────────────────────────────────────────────────────────────────────────
-- RLS: authenticated role ko sab allow (project convention — single-owner app)
-- ─────────────────────────────────────────────────────────────────────────────
alter table public.purchase_orders       enable row level security;
alter table public.purchase_order_items   enable row level security;
alter table public.push_subscriptions     enable row level security;

drop policy if exists "Allow authenticated access" on public.purchase_orders;
create policy "Allow authenticated access"
  on public.purchase_orders
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Allow authenticated access" on public.purchase_order_items;
create policy "Allow authenticated access"
  on public.purchase_order_items
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Allow authenticated access" on public.push_subscriptions;
create policy "Allow authenticated access"
  on public.push_subscriptions
  to authenticated
  using (true)
  with check (true);

-- ─────────────────────────────────────────────────────────────────────────────
-- Auto-update date_updated on UPDATE (convention: transaction_list-style)
-- ─────────────────────────────────────────────────────────────────────────────
create or replace function public.touch_purchase_orders()
returns trigger language plpgsql as $$
begin
  new.date_updated = now();
  return new;
end;
$$;

drop trigger if exists purchase_orders_touch on public.purchase_orders;
create trigger purchase_orders_touch
  before update on public.purchase_orders
  for each row execute function public.touch_purchase_orders();

create or replace function public.touch_push_subscriptions()
returns trigger language plpgsql as $$
begin
  new.date_updated = now();
  return new;
end;
$$;

drop trigger if exists push_subscriptions_touch on public.push_subscriptions;
create trigger push_subscriptions_touch
  before update on public.push_subscriptions
  for each row execute function public.touch_push_subscriptions();



-- ════════════════════════════════════════════════════════════════════════════
-- >>>  20260816_allow_developer_role.sql
-- ════════════════════════════════════════════════════════════════════════════
-- ============================================================================
-- 20260816_allow_developer_role.sql
-- profiles.role me 'developer' allow karne ke liye CHECK constraint update.
--
-- Problem: /users/[id]/edit par kisi admin ko 'Developer' role set karne par
-- "violates check constraint profiles_role_check" error aata tha. App aur APIs
-- ab 'developer' role support karte hain (api-auth me admin-equivalent) lekin
-- profiles_role_check abhi sirf ('admin','staff','client') allow karta hai.
--
-- Note: CHECK constraint RLS/trigger ko bypass karne wale service-role se bhi
-- enforce hota hai — isliye sirf migration hi fix karega.
-- ============================================================================

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('admin', 'staff', 'client', 'developer'));



-- ════════════════════════════════════════════════════════════════════════════
-- >>>  20260821_product_image_path_nullable.sql
-- ════════════════════════════════════════════════════════════════════════════
-- Fix: naya product add karte samay 23502 error
-- "null value in column \"image_path\" of relation \"product_list\" violates not-null constraint"
-- MariaDB restore ke baad image_path NOT NULL ban gaya tha; design me ye nullable hai
-- (product-image API remove par image_path = null set karta hai).
--
-- Supabase Dashboard -> SQL Editor me ye run karein:

ALTER TABLE public.product_list ALTER COLUMN image_path DROP NOT NULL;



-- ════════════════════════════════════════════════════════════════════════════
-- >>>  20260815_unique_mechanic_link.sql
-- ════════════════════════════════════════════════════════════════════════════
-- ============================================================================
-- 20260815_unique_mechanic_link.sql
-- Ek mechanic sirf ek user (profile) se link ho sakta hai (1:1).
--
-- Problem: profiles.mechanic_id bina restriction ke multiple profiles par ek hi
-- mechanic ko point kar sakta tha — do users ek hi mechanic ke roop mein
-- attendance check-in kar sakte the (double entries, ambiguous attendance).
--
-- Fix: Partial unique index — mechanic_id null (bina login wala mechanic)
-- allowed hai, par ek non-null mechanic_id sirf ek hi profile par ho sakta hai.
--
-- Apply: Supabase SQL Editor me run karo (ek baar, idempotent).
-- ============================================================================

-- ── 1) Agar already koi duplicate link ho to har mechanic ke liye sirf ek
--       profile ka link rakho (deterministic: min uuid), baaki ke links null
--       karo taaki unique index ban sake.
with keep as (
  select distinct on (mechanic_id) id, mechanic_id
  from public.profiles
  where mechanic_id is not null
  order by mechanic_id, id
)
update public.profiles p
set mechanic_id = null
where p.mechanic_id is not null
  and not exists (
    select 1 from keep k
    where k.mechanic_id = p.mechanic_id and k.id = p.id
  );

-- ── 2) 1:1 enforcement — unique partial index (null allowed, duplicates nahi)
create unique index if not exists profiles_mechanic_id_unique
  on public.profiles (mechanic_id)
  where mechanic_id is not null;



-- ════════════════════════════════════════════════════════════════════════════
-- >>>  20260821_dashboard_performance_rpcs.sql
-- ════════════════════════════════════════════════════════════════════════════
-- ══════════════════════════════════════════════════════════════════════════════
-- DASHBOARD PERFORMANCE RPCs — 40+ client calls → 3 server calls
-- ══════════════════════════════════════════════════════════════════════════════
-- Run this migration in your CLIENT Supabase project (not the licensing one).
-- These functions run inside PostgreSQL — all aggregation server-side.

-- ──────────────────────────────────────────────────────────────────────────────
-- 1) get_dashboard_stats — job counts + client/mech count + today revenue
--    Replaces: ~17 separate count/select queries
-- ──────────────────────────────────────────────────────────────────────────────
create or replace function public.get_dashboard_stats(
  p_today_start text,
  p_today_end   text
)
returns jsonb
language plpgsql
security definer
stable
as $$
declare
  result jsonb;
begin
  select jsonb_build_object(
    'totalJobs',       (select count(*) from public.transaction_list where del_status = 0),
    'pendingJobs',     (select count(*) from public.transaction_list where del_status = 0 and status = 0),
    'inProgressJobs',  (select count(*) from public.transaction_list where del_status = 0 and status = 1),
    'finishedJobs',    (select count(*) from public.transaction_list where del_status = 0 and status = 2),
    'paidJobs',        (select count(*) from public.transaction_list where del_status = 0 and status = 3),
    'cancelledJobs',   (select count(*) from public.transaction_list where del_status = 0 and status = 4),
    'deliveredJobs',   (select count(*) from public.transaction_list where del_status = 0 and status = 5),
    'totalClients',    (select count(*) from public.client_list where delete_flag = 0),
    'totalMechanics',  (select count(*) from public.mechanic_list where delete_flag = 0 and status = 1),
    'todayRepair',     (select coalesce(sum(amount), 0) from public.transaction_list where status = 5 and del_status = 0 and date_completed >= p_today_start::timestamptz and date_completed <= p_today_end::timestamptz),
    'todayDirect',     (select coalesce(sum(total_amount), 0) from public.direct_sales where date_created >= p_today_start::timestamptz and date_created <= p_today_end::timestamptz)
  ) into result;

  return result;
end;
$$;

-- ──────────────────────────────────────────────────────────────────────────────
-- 2) get_monthly_revenue — last N months revenue data
--    Replaces: 12-month loop with 24 sequential queries → 1 call
-- ──────────────────────────────────────────────────────────────────────────────
create or replace function public.get_monthly_revenue(p_months int default 12)
returns jsonb
language plpgsql
security definer
stable
as $$
declare
  result jsonb;
  month_label text;
  month_revenue numeric;
  months_arr jsonb := '[]'::jsonb;
  i int;
  m_date date;
  m_start timestamptz;
  m_end timestamptz;
begin
  for i in 0 .. (p_months - 1) loop
    m_date := date_trunc('month', current_date) - (i || ' months')::interval;
    m_start := (date_trunc('month', m_date))::timestamptz;
    m_end   := (date_trunc('month', m_date) + interval '1 month - 1 second')::timestamptz;

    month_label := to_char(m_date, 'Mon YY');

    select coalesce(sum(repair_rev + direct_rev), 0) into month_revenue
    from (
      select coalesce(sum(amount), 0) as repair_rev, 0 as direct_rev
        from public.transaction_list
       where status = 5 and del_status = 0
         and date_completed >= m_start and date_completed <= m_end
      union all
      select 0 as repair_rev, coalesce(sum(total_amount), 0) as direct_rev
        from public.direct_sales
       where date_created >= m_start and date_created <= m_end
    ) t;

    months_arr := months_arr || jsonb_build_object(
      'month', month_label,
      'revenue', month_revenue
    );
  end loop;

  -- Reverse so oldest first
  result := (
    select jsonb_agg(elem)
    from (select elem from jsonb_array_elements(months_arr) with ordinality AS t(elem, pos) order by t.pos desc) sub
  );

  return coalesce(result, '[]'::jsonb);
end;
$$;

-- ──────────────────────────────────────────────────────────────────────────────
-- 3) get_financial_summary — date-range financial summary
--    Replaces: ~12 separate queries for sales, parts, salary, expenses etc.
-- ──────────────────────────────────────────────────────────────────────────────
create or replace function public.get_financial_summary(
  p_from text,
  p_to   text
)
returns jsonb
language plpgsql
security definer
stable
as $$
declare
  result jsonb;
  v_from timestamptz;
  v_to   timestamptz;
  v_repair_inc  numeric;
  v_direct_inc  numeric;
  v_total_sales numeric;
  v_parts_trans numeric;
  v_parts_direct numeric;
  v_parts_cost  numeric;
  v_discounts   numeric;
  v_salary      numeric;
  v_loan_paid   numeric;
  v_expenses    numeric;
  v_tx_ids      int[];
  v_ds_ids      int[];
begin
  v_from := (p_from || 'T00:00:00+05:30')::timestamptz;
  v_to   := (p_to || 'T23:59:59+05:30')::timestamptz;

  -- Repair + Direct income
  select coalesce(sum(amount), 0) into v_repair_inc
    from public.transaction_list
   where status = 5 and del_status = 0
     and date_completed >= v_from and date_completed <= v_to;

  select coalesce(sum(total_amount), 0) into v_direct_inc
    from public.direct_sales
   where date_created >= v_from and date_created <= v_to;

  v_total_sales := v_repair_inc + v_direct_inc;

  -- Parts cost — actual cost_price from products, fallback 90% of selling price
  select array_agg(id) into v_tx_ids
    from public.transaction_list
   where status = 5 and del_status = 0
     and date_completed >= v_from and date_completed <= v_to;

  select array_agg(id) into v_ds_ids
    from public.direct_sales
   where date_created >= v_from and date_created <= v_to;

  select coalesce(sum(
    tp.qty * case
      when p.cost_price is not null and p.cost_price > 0 then p.cost_price
      else tp.price * 0.9
    end
  ), 0) into v_parts_trans
  from public.transaction_products tp
  left join public.product_list p on p.id = tp.product_id
  where v_tx_ids is not null and tp.transaction_id = any(v_tx_ids);

  select coalesce(sum(
    di.qty * case
      when p.cost_price is not null and p.cost_price > 0 then p.cost_price
      else di.price * 0.9
    end
  ), 0) into v_parts_direct
  from public.direct_sale_items di
  left join public.product_list p on p.id = di.product_id
  where v_ds_ids is not null and di.sale_id = any(v_ds_ids);

  v_parts_cost := v_parts_trans + v_parts_direct;

  -- Discounts
  select coalesce(sum(discount), 0) into v_discounts
    from public.client_payments
   where payment_date >= p_from and payment_date <= p_to;

  -- Salary (attendance-based)
  select coalesce(sum(
    case
      when a.status = 1 then m.daily_salary
      when a.status = 3 then m.daily_salary / 2
      else 0
    end
  ), 0) into v_salary
  from public.attendance_list a
  join public.mechanic_list m on m.id = a.mechanic_id
  where a.curr_date >= p_from and a.curr_date <= p_to
    and a.status in (1, 3);

  -- Loan paid
  select coalesce(sum(amount_paid), 0) into v_loan_paid
    from public.loan_payments
   where payment_date >= p_from and payment_date <= p_to;

  -- Expenses
  select coalesce(sum(amount), 0) into v_expenses
    from public.expense_list
   where date_created >= v_from and date_created <= v_to;

  result := jsonb_build_object(
    'totalSales',   v_total_sales,
    'partsCost',    v_parts_cost,
    'grossProfit',  v_total_sales - v_parts_cost,
    'discounts',    v_discounts,
    'salary',       v_salary,
    'loanPaid',     v_loan_paid,
    'expenses',     v_expenses,
    'totalOutflow', v_discounts + v_salary + v_loan_paid + v_expenses,
    'netProfit',    (v_total_sales - v_parts_cost) - (v_discounts + v_salary + v_loan_paid + v_expenses)
  );

  return result;
end;
$$;

-- Grant access to authenticated users
grant execute on function public.get_dashboard_stats(text, text) to authenticated;
grant execute on function public.get_monthly_revenue(int) to authenticated;
grant execute on function public.get_financial_summary(text, text) to authenticated;

-- ──────────────────────────────────────────────────────────────────────────────
-- 4) get_technician_metrics — per-mechanic productivity for a date range
--    Returns: jobs completed, revenue, commission, attendance breakdown
-- ──────────────────────────────────────────────────────────────────────────────
create or replace function public.get_technician_metrics(
  p_from text,
  p_to   text
)
returns jsonb
language plpgsql
security definer
stable
as $$
declare
  result jsonb;
  v_from date := p_from::date;
  v_to   date := p_to::date;
begin
  select jsonb_agg(row_to_json(t)) into result
  from (
    select
      m.id,
      m.firstname || ' ' || coalesce(m.lastname, '') as name,
      m.designation,
      m.daily_salary,
      m.commission_percent,
      m.image_path,

      -- Jobs completed (status 5 = delivered)
      coalesce(job_stats.jobs_completed, 0) as jobs_completed,
      coalesce(job_stats.jobs_revenue, 0) as jobs_revenue,
      coalesce(job_stats.jobs_commission, 0) as jobs_commission,

      -- Attendance
      coalesce(att_stats.full_days, 0) as full_days,
      coalesce(att_stats.half_days, 0) as half_days,
      coalesce(att_stats.absent_days, 0) as absent_days,
      coalesce(att_stats.total_attended, 0) as total_attended,
      coalesce(att_stats.working_days, 0) as working_days,

      -- Salary earned (attendance-based)
      coalesce(att_stats.salary_earned, 0) as salary_earned,

      -- Avg repair time in hours (date_completed - date_created for delivered jobs)
      job_stats.avg_repair_hours

    from public.mechanic_list m

    left join lateral (
      select
        count(*) as jobs_completed,
        coalesce(sum(t.amount), 0) as jobs_revenue,
        coalesce(sum(t.mechanic_commission_amount), 0) as jobs_commission,
        case when count(*) > 0
          then round(extract(epoch from avg(t.date_completed - t.date_created)) / 3600, 1)
          else null
        end as avg_repair_hours
      from public.transaction_list t
      where t.mechanic_id = m.id
        and t.status = 5
        and t.del_status = 0
        and t.date_completed >= (v_from || 'T00:00:00+05:30')::timestamptz
        and t.date_completed <= ((v_to || 'T23:59:59+05:30')::timestamptz)
    ) job_stats on true

    left join lateral (
      select
        count(*) filter (where a.status = 1) as full_days,
        count(*) filter (where a.status = 3) as half_days,
        count(*) filter (where a.status = 2) as absent_days,
        count(*) filter (where a.status in (1, 3)) as total_attended,
        count(*) as working_days,
        coalesce(sum(
          case
            when a.status = 1 then m.daily_salary
            when a.status = 3 then m.daily_salary / 2
            else 0
          end
        ), 0) as salary_earned
      from public.attendance_list a
      where a.mechanic_id = m.id
        and a.curr_date >= v_from
        and a.curr_date <= v_to
    ) att_stats on true

    where m.delete_flag = 0 and m.status = 1
    order by job_stats.jobs_completed desc nulls last
  ) t;

  return coalesce(result, '[]'::jsonb);
end;
$$;

grant execute on function public.get_technician_metrics(text, text) to authenticated;



-- ════════════════════════════════════════════════════════════════════════════
-- >>>  20260824_job_item_locations.sql
-- ════════════════════════════════════════════════════════════════════════════
-- ============================================================================
-- 20260824_job_item_locations.sql
-- Job items ki physical location tracking — inventory ke `locations` master ka
-- reuse, bina kisi naye table ke.
--
-- Concept:
--   locations.kind = 'inventory' → permanent racks (spares/stock) [existing rows]
--   locations.kind = 'job'       → temporary spots (counter/shelf/tray) jahan
--                                  customer items repair-flow me rakhe jaate hain
--
-- transaction_list.location_id (nullable FK) source-of-truth hai.
-- Legacy `uniq_id` text column DUAL-WRITE ke liye rehta hai — jab bhi
-- location_id set ho, app uska readable path (sirf spot naam) uniq_id me
-- likhta hai, taaki purane screens/search/export bina badle kaam karein.
--
-- Backfill: live jobs ki purani non-empty uniq_id values ko kind='job'
-- location rows banakar link kar deta hai (purana data delete nahi hota).
-- Idempotent: baar baar run karne se error nahi aayega.
-- Apply: Supabase SQL Editor me run karo (ek baar).
-- ============================================================================

-- 1. locations.kind — 'inventory' | 'job' (default purane rows ke liye)
alter table public.locations
  add column if not exists kind text not null default 'inventory';

create index if not exists locations_kind_idx on public.locations (kind);

-- 2. transaction_list.location_id — nullable FK
alter table public.transaction_list
  add column if not exists location_id integer references public.locations(id);

create index if not exists transaction_list_location_idx
  on public.transaction_list (location_id);

-- 3. Backfill: live jobs ki uniq_id → kind='job' location rows (dupe-safe)
--    NOTE: locations.zone NOT NULL hai — job-spots ke liye '' (empty) use hota hai
insert into public.locations (zone, rack, kind)
select distinct '', t.uniq_id, 'job'
from public.transaction_list t
where t.del_status = 0
  and coalesce(t.uniq_id, '') <> ''
  and not exists (
    select 1 from public.locations l
    where l.kind = 'job' and l.rack = t.uniq_id and l.zone = ''
  );

-- 4. Link live jobs to their backfilled location rows
update public.transaction_list t
set location_id = l.id
from public.locations l
where l.kind = 'job'
  and l.rack = t.uniq_id
  and l.zone = ''
  and t.del_status = 0
  and coalesce(t.uniq_id, '') <> ''
  and t.location_id is null;

notify pgrst, 'reload schema';



-- ════════════════════════════════════════════════════════════════════════════
-- >>>  20260911_rls_lockdown.sql
-- ════════════════════════════════════════════════════════════════════════════
-- ════════════════════════════════════════════════════════════════════════
-- 20260911_rls_lockdown.sql
-- RLS lockdown — baaki sab public tables par bhi RLS (defense-in-depth).
--
-- Problem (20260911 audit):
--   Frontend bundle me PUBLIC anon key hota hai; bina RLS ke table REST API
--   se anon + authenticated dono ke liye bilkul khule rehte hain. 20260910 ke
--   hardening ne sirf 7 tables cover kiye — ye migration baaki tables ko bhi
--   band karta hai:
--
--   • Staff business tables (client_list, mechanic_list, expense_list, ...)
--     → sirf admin/staff/developer CRUD (developer = dev-team, app ke
--       requireStaff/requireAdmin jaisa, sab staff data dikhna chahiye).
--       Client portal ko client_list/profiles par apna data (self) dikhta
--       hai — isliye client_self policies bhi.
--   • licenses / activations / client_credentials (seller/developer/provision)
--     → SIRF service-role (RLS ON, koi anon/auth policy nahi). App inhe
--       sirf service-role libs (license-admin.ts, client-creds.ts) se touch
--       karta hai — service_role RLS bypass karta hai, sab kaam chalega.
--   • Purana `with check (true)` hole band kiya (transaction_list,
--     client_payments, direct_sales, client_loans, purchase_orders,
--     purchase_order_items, push_subscriptions) — ab insert/update bhi role
--     gated hai; koi client arbitrary financial rows forge nahi kar sakta.
--   • push_subscriptions par user-own policy (har user sirf apne device
--     ka sub), staff sab dekh sakta hai (admin send ke liye).
--
-- App breaking nahi hoga: saare staff pages authenticated (staff/admin/
-- developer) ke roop me hi chalte hain aur in policies ke under hi query
-- karte hain. profiles self-update role/client_id immutable rakhta hai —
-- koi client/staff khud ko admin nahi bana sakta.
--
-- FULLY IDEMPOTENT (28 Aug fix): har create policy se pehle `drop if
-- exists` hai → partial-apply ke baad bhi poora file dubara run karna safe
-- (no "policy already exists" abort). PostgreSQL `for select, update` INVALID
-- hai — profiles policy ko 2 policy me split kiya (rlslock_profiles_staff =
-- select; rlslock_profiles_staff_update = update, role/client_id immutable).
--
-- RECURSION FIX (28 Aug, LIVE 42P17): profiles ki apni policies khud profiles
-- ko subquery karti thin → "infinite recursion detected in policy for relation
-- profiles" → authenticated reads par 500. Fix: role/client_id lookup ab
-- SECURITY DEFINER helper functions (get_my_role / get_my_client_id /
-- is_frontend_staff) me hai — function body mai RLS bypass (owner=postgres,
-- superuser) isliye koi recursion nahi. policies function call karti hain.
-- → Pura file DUBARA apply karlo (idempotent — purani policies drop hoti hain,
-- nayi function-based banti hain).
--
-- Apply: Supabase SQL Editor me run karo (ek baar, idempotent), phir
-- `node scripts/verify-rls.cjs` + scripts/check_rls.sql se verify.
--
-- ═══ LIVE-DB pre-flight (28 Aug 2026, PostgREST + service-role probe) ═══
--   • is shop project me `licenses`/`activations`/`client_credentials` tables
--     HAI NAHI (404) — wo central `vtech_licence` project me hain. Isliye
--     provision wale alters `to_regclass` guard me hain.
--   • Baaki sab target tables pe anon reads pehle se = 0 rows (RLS ON live) —
--     ye migration unhe "defense-in-depth" ke liye dubara role-gate karta hai.
--   • client_own policies (portal_transaction_list_client_own /
--     portal_client_payments_client_own) live present hain — section 6 inhe
--     DROP NAHI karta (sirf *_staff policies replace hoti hain), client portal
--     chalta rahega.
--   • HOLE LIVE CONFIRMED (client user ne apni token se client_payments par
--     INSERT @201 chalaya, marker row cleanup kar diya) → section 6 ka
--     `with check (true)` fix is DB par REAL kaam karta hai.
--   • developer role: purani policies me admin/staff hi tha → ye migration
--     developer ko bhi deta hai (app ke requireStaff/requireAdmin semantics).
--   • APP-BREAK AUDIT (browser/user-JWT path, 28 Aug): staff/admin/developer
--     ki saari UI reads+CRUD (jobs/clients/payments/inventory/reports...) in
--     19+portal+PO tables par hai → migration ki staff policies (all) inhe
--     cover karti hain. users/new + users/[id]/edit ki profiles writes
--     service-role /api/admin/* se hoti hain (browser sirf read) → safe.
--     Client portal sirf /api/client/* (service-role) → RLS se unaffected;
--     RootClient ke sirf profiles(own row)+system_info reads hai (system_info
--     migration me nahi hai). RPC (get_dashboard_stats etc.) untouched + tables
--     already locked → dashboard aaj kaam karta hai, waisa hi rahega.
--     → PROJECT BREAK NAHI HOGA. reCAP: sirf sachcha closing = with-check hole
--     (client forge) + staff self-escalation (profile policies immutable).
--   • ══ SNAPSHOT-DUMP re-check (28 Aug, 62 policies wala pg_policies dump) ══
--     • profiles LIVE me escalation-open tha: "Allow users update own profile"
--       (auth.uid()=id, role/client_id free) → koi bhi khud ko admin bana leta
--       aaj. Section 4 inhe drop karke immutable versions deta hai.
--     • service_list + direct_sale_items LIVE me "Allow authenticated access"
--       (read+WRITE kisi bhi logged-in user ko) the → migration me values add
--       kar diye (staff gate) — warna ye hole client ko khula rehta.
--     • locations + location_zones/racks/boxes/bins LIVE me `to public` CRUD
--       policies hain (naam "Staff can..." par role = public = anon samet).
--       Ye intentionally is migration me NAHI — alag review/follow-up.
--   ════════════════════════════════════════════════════════════════════════

-- ── 1) RLS ON (idempotent) ──────────────────────────────────────────────
alter table public.client_list                    enable row level security;
alter table public.profiles                       enable row level security;
alter table public.mechanic_list                  enable row level security;
alter table public.expense_list                   enable row level security;
alter table public.lender_list                    enable row level security;
alter table public.loan_payments                  enable row level security;
alter table public.attendance_list                enable row level security;
alter table public.inventory_list                 enable row level security;
alter table public.product_list                   enable row level security;
alter table public.product_locations              enable row level security;
alter table public.job_id_counter                 enable row level security;
alter table public.transaction_products           enable row level security;
alter table public.transaction_services           enable row level security;
alter table public.transaction_images             enable row level security;
alter table public.advance_payments               enable row level security;
alter table public.mechanic_salary_history        enable row level security;
alter table public.mechanic_commission_history    enable row level security;
alter table public.service_list                   enable row level security;
alter table public.direct_sale_items              enable row level security;

-- Provisioning tables (licenses/activations/client_credentials) — SIRF service-
-- role (RLS ON + koi policy nahi → anon/authenticated = 0, service_role bypass).
-- NOTE (live-db check 2026-08-28): ye 3 tables is shop project me EXIST nahi
-- karti — wo central `vtech_licence` project me hain. `to_regclass` guard isliye
-- taki migration is DB par bhi bina crash chale aur license-wale project par bhi.
do $$
begin
  if to_regclass('public.licenses') is not null then
    alter table public.licenses enable row level security;
  end if;
  if to_regclass('public.activations') is not null then
    alter table public.activations enable row level security;
  end if;
  if to_regclass('public.client_credentials') is not null then
    alter table public.client_credentials enable row level security;
  end if;
end $$;

-- Portal financial / PO tables — idempotent RLS ON (kuch manual "step 1" fixes/
-- SQL editor se applied the; enable already hota to no-op, warna policies
-- bina RLS ke silent-inert reh kar hole khola chhod deti. Ye guarantee karta hai
-- ki section 6/7 ke policies actually enforce hon).
alter table public.transaction_list          enable row level security;
alter table public.client_payments           enable row level security;
alter table public.direct_sales              enable row level security;
alter table public.client_loans              enable row level security;
alter table public.purchase_orders           enable row level security;
alter table public.purchase_order_items      enable row level security;
alter table public.push_subscriptions        enable row level security;

-- ── 1.5) RLS policies ke liye helper functions (SECURITY DEFINER) ────────
-- Ye standard Supabase pattern hai: policy ke andar profiles ko subquery karna
-- recursion (42P17) deta hai jab profiles ki apni policies bhi profiles ko
-- subquery karein. security definer + owner (postgres/superuser) = function
-- body me RLS bypass → recursion break. auth.uid() caller ka uid deta hai.
-- `set search_path = public` hijack-se bachata hai; saare refs qualified.
create or replace function public.get_my_role()
returns text
language sql
security definer
stable
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.get_my_client_id()
returns bigint
language sql
security definer
stable
set search_path = public
as $$
  select client_id from public.profiles where id = auth.uid();
$$;

create or replace function public.is_frontend_staff()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select coalesce((select role from public.profiles where id = auth.uid()), '') in ('admin', 'staff', 'developer');
$$;

-- ── 2) Purani policies hatao (Allow-all / broad auth / duplicate) ───────
do $$
declare p record;
begin
  for p in
    select policyname, tablename
    from pg_policies
    where schemaname = 'public'
      and tablename in (
        'client_list', 'profiles', 'mechanic_list', 'expense_list',
        'lender_list', 'loan_payments', 'attendance_list', 'inventory_list',
        'product_list', 'product_locations', 'job_id_counter',
        'transaction_products', 'transaction_services', 'transaction_images',
        'advance_payments', 'mechanic_salary_history',
        'mechanic_commission_history', 'service_list', 'direct_sale_items',
        'licenses', 'activations',
        'client_credentials'
      )
  loop
    execute format('drop policy if exists %I on public.%I', p.policyname, p.tablename);
  end loop;
end $$;

-- ── 3) Staff/Admin business CRUD policies ───────────────────────────────
-- Role check: profile wala authenticated user hi — anon/ghost authenticated user
-- ko in tables par kuch nahi (using + with check dono role-gated).
-- Har create se pehle drop-if-exists (idempotent re-run ke liye).

drop policy if exists rlslock_client_list_staff on public.client_list;
create policy rlslock_client_list_staff on public.client_list
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

drop policy if exists rlslock_mechanic_list_staff on public.mechanic_list;
create policy rlslock_mechanic_list_staff on public.mechanic_list
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

drop policy if exists rlslock_expense_list_staff on public.expense_list;
create policy rlslock_expense_list_staff on public.expense_list
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

drop policy if exists rlslock_lender_list_staff on public.lender_list;
create policy rlslock_lender_list_staff on public.lender_list
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

drop policy if exists rlslock_loan_payments_staff on public.loan_payments;
create policy rlslock_loan_payments_staff on public.loan_payments
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

drop policy if exists rlslock_attendance_list_staff on public.attendance_list;
create policy rlslock_attendance_list_staff on public.attendance_list
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

drop policy if exists rlslock_inventory_list_staff on public.inventory_list;
create policy rlslock_inventory_list_staff on public.inventory_list
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

drop policy if exists rlslock_product_list_staff on public.product_list;
create policy rlslock_product_list_staff on public.product_list
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

drop policy if exists rlslock_product_locations_staff on public.product_locations;
create policy rlslock_product_locations_staff on public.product_locations
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

drop policy if exists rlslock_job_id_counter_staff on public.job_id_counter;
create policy rlslock_job_id_counter_staff on public.job_id_counter
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

drop policy if exists rlslock_transaction_products_staff on public.transaction_products;
create policy rlslock_transaction_products_staff on public.transaction_products
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

drop policy if exists rlslock_transaction_services_staff on public.transaction_services;
create policy rlslock_transaction_services_staff on public.transaction_services
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

drop policy if exists rlslock_transaction_images_staff on public.transaction_images;
create policy rlslock_transaction_images_staff on public.transaction_images
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

drop policy if exists rlslock_advance_payments_staff on public.advance_payments;
create policy rlslock_advance_payments_staff on public.advance_payments
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

drop policy if exists rlslock_mech_salary_staff on public.mechanic_salary_history;
create policy rlslock_mech_salary_staff on public.mechanic_salary_history
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

drop policy if exists rlslock_mech_commission_staff on public.mechanic_commission_history;
create policy rlslock_mech_commission_staff on public.mechanic_commission_history
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

-- (Live-dump finding 28 Aug: service_list + direct_sale_items "Allow authenticated
-- access" the = kisi bhi logged-in user ko read+write. Client ho to bhi! Staff UI
-- tables hain (service catalog, POS items) — isliye staff/admin/developer gate.)
drop policy if exists rlslock_service_list_staff on public.service_list;
create policy rlslock_service_list_staff on public.service_list
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

drop policy if exists rlslock_direct_sale_items_staff on public.direct_sale_items;
create policy rlslock_direct_sale_items_staff on public.direct_sale_items
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

-- ── 4) profiles — staff/admin select + client self read; update immutable ──
-- Note: profiles ka INSERT + DELETE sirf service-role hota hai (admin
-- create-user / delete-user API, client onboard upsert) — isliye authenticated
-- ko in tables par select/update se zyada nahi: koi bhi browser se role
-- escalate / user bana / delete nahi kar sakta.
--
-- 28 Aug fix: `for select, update` PostgreSQL me INVALID hai — 2 alag policy:
-- rlslock_profiles_staff (SELECT) + rlslock_profiles_staff_update (UPDATE).
drop policy if exists rlslock_profiles_staff on public.profiles;
create policy rlslock_profiles_staff on public.profiles
  for select to authenticated
  using (public.is_frontend_staff());

-- Staff/admin khud-apna profile update kar sakta hai, par OWN ROW + ROLE and
-- CLIENT_ID immutable — warna koi staff browser se 'update profiles set
-- role=admin' chala ke khud ko admin bana leta. Admin ki role-changes
-- /api/admin/update-profile (service-role) se hoti hain, isse break nahi.
drop policy if exists rlslock_profiles_staff_update on public.profiles;
create policy rlslock_profiles_staff_update on public.profiles
  for update to authenticated
  using (id = auth.uid())
  with check (
    id = auth.uid()
    and public.is_frontend_staff()
    and coalesce(role, '') = public.get_my_role()
    and coalesce(client_id, -1) is not distinct from public.get_my_client_id()
  );

drop policy if exists rlslock_profiles_client_self on public.profiles;
create policy rlslock_profiles_client_self on public.profiles
  for select to authenticated
  using (id = auth.uid());

-- Self-update: apna profile update allowed, par ROLE + CLIENT_ID immutable —
-- warna koi client/staff khud ko 'admin' bana leta (privilege escalation).
drop policy if exists rlslock_profiles_client_self_update on public.profiles;
create policy rlslock_profiles_client_self_update on public.profiles
  for update to authenticated
  using (id = auth.uid())
  with check (
    id = auth.uid()
    and coalesce(role, '') = public.get_my_role()
    and coalesce(client_id, -1) is not distinct from public.get_my_client_id()
  );

-- ── 5) client_list — client ko sirf apna record ──────────────────────────
drop policy if exists rlslock_client_list_client_self on public.client_list;
create policy rlslock_client_list_client_self on public.client_list
  for select to authenticated
  using (
    public.get_my_role() = 'client'
    and id = public.get_my_client_id()
  );

-- ── 6) Portal financial tables — `with check (true)` hole band karo ───────
-- Ab insert/update bhi sirf staff/admin (client kabhi forge nahi kar sakta).
drop policy if exists portal_transaction_list_staff on public.transaction_list;
create policy portal_transaction_list_staff on public.transaction_list
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

drop policy if exists portal_client_payments_staff on public.client_payments;
create policy portal_client_payments_staff on public.client_payments
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

drop policy if exists portal_direct_sales_staff on public.direct_sales;
create policy portal_direct_sales_staff on public.direct_sales
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

drop policy if exists portal_client_loans_staff on public.client_loans;
create policy portal_client_loans_staff on public.client_loans
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

-- ── 7) Purchase orders + Push subscriptions — broad auth band karo ───────
drop policy if exists "Allow authenticated access" on public.purchase_orders;
drop policy if exists rlslock_purchase_orders_staff on public.purchase_orders;
create policy rlslock_purchase_orders_staff on public.purchase_orders
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

drop policy if exists "Allow authenticated access" on public.purchase_order_items;
drop policy if exists rlslock_purchase_order_items_staff on public.purchase_order_items;
create policy rlslock_purchase_order_items_staff on public.purchase_order_items
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

drop policy if exists "Allow authenticated access" on public.push_subscriptions;
drop policy if exists rlslock_push_subscriptions_staff on public.push_subscriptions;
create policy rlslock_push_subscriptions_staff on public.push_subscriptions
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

drop policy if exists rlslock_push_subscriptions_self on public.push_subscriptions;
create policy rlslock_push_subscriptions_self on public.push_subscriptions
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- ── 8) Report: lockdown se cover hue tables ──────────────────────────────
select relname as table, relrowsecurity as rls_enabled
from pg_class
where relnamespace = 'public'::regnamespace
  and relname in (
    'client_list','profiles','mechanic_list','expense_list','lender_list',
    'loan_payments','attendance_list','inventory_list','product_list',
    'product_locations','job_id_counter','transaction_products',
    'transaction_services','transaction_images','advance_payments',
    'mechanic_salary_history','mechanic_commission_history',
    'service_list','direct_sale_items',
    'licenses','activations','client_credentials',
    'transaction_list','client_payments','direct_sales','client_loans',
    'purchase_orders','purchase_order_items','push_subscriptions'
  )
order by relname;


-- ════════════════════════════════════════════════════════════════════════════
-- >>>  20260829_clients_page_financials_rpc.sql
-- ════════════════════════════════════════════════════════════════════════════
-- CLIENTS PAGE PERFORMANCE RPC — collapses 5 full-table JS aggregations into
-- one server-side aggregate. FAST PATH for /clients (see src/lib/server-clients.ts).
-- Idempotent. Run in the CLIENT Supabase project.
create or replace function public.get_clients_page_financials()
returns jsonb
language sql
security definer
stable
as $$
  with active_loans as (
    select id, client_id, total_payable
    from public.client_loans
    where status = 1
  ),
  repair_agg as (
    select
      case when client_name ~ '^\d+$' then client_name::int else null end as client_id,
      coalesce(sum(amount), 0) as repair_billed
    from public.transaction_list
    where status = 5
    group by 1
    having case when client_name ~ '^\d+$' then client_name::int else null end is not null
  ),
  direct_agg as (
    select
      client_id,
      coalesce(sum(total_amount), 0) as direct_sales_billed
    from public.direct_sales
    group by client_id
  ),
  service_pay_agg as (
    select
      client_id,
      coalesce(sum(amount + coalesce(discount, 0)), 0) as service_paid
    from public.client_payments
    where loan_id is null or loan_id = 0
    group by client_id
  ),
  loan_given_agg as (
    select
      client_id,
      coalesce(sum(total_payable), 0) as active_loan_given
    from active_loans
    group by client_id
  ),
  loan_repaid_agg as (
    select
      cp.client_id,
      coalesce(sum(cp.amount + coalesce(cp.discount, 0)), 0) as loan_repaid
    from public.client_payments cp
    inner join active_loans al on al.id = cp.loan_id
    group by cp.client_id
  ),
  last_txn_agg as (
    select
      case when client_name ~ '^\d+$' then client_name::int else null end as client_id,
      max(date_created) as last_txn_date
    from public.transaction_list
    group by 1
    having case when client_name ~ '^\d+$' then client_name::int else null end is not null
  ),
  all_ids as (
    select client_id from repair_agg
    union
    select client_id from direct_agg
    union
    select client_id from service_pay_agg
    union
    select client_id from loan_given_agg
    union
    select client_id from loan_repaid_agg
    union
    select client_id from last_txn_agg
  )
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'client_id', i.client_id,
        'repair_billed', coalesce(r.repair_billed, 0),
        'direct_sales_billed', coalesce(d.direct_sales_billed, 0),
        'service_paid', coalesce(sp.service_paid, 0),
        'active_loan_given', coalesce(lg.active_loan_given, 0),
        'loan_repaid', coalesce(lr.loan_repaid, 0),
        'last_txn_date', lt.last_txn_date
      )
      order by i.client_id
    ),
    '[]'::jsonb
  )
  from all_ids i
  left join repair_agg r on r.client_id = i.client_id
  left join direct_agg d on d.client_id = i.client_id
  left join service_pay_agg sp on sp.client_id = i.client_id
  left join loan_given_agg lg on lg.client_id = i.client_id
  left join loan_repaid_agg lr on lr.client_id = i.client_id
  left join last_txn_agg lt on lt.client_id = i.client_id;
$$;

grant execute on function public.get_clients_page_financials() to authenticated;
