-- ============================================================================
-- 00_full_schema.sql
-- Consolidated idempotent schema — full project setup.
--
-- Run on: Any fresh Supabase / PostgreSQL database.
-- Order:    ENUMS → TABLES → INDEXES → FUNCTIONS → TRIGGERS → SEED
-- Safe:     IF NOT EXISTS / DROP IF EXISTS — repeatable, no conflicts.
--
-- Source: Original working DB (rklyznlrcrysdpksltxm.supabase.co)
--         Queried via PostgREST REST API + schema introspection.
-- NOTE:    Original DB has NO RLS enabled. This dump intentionally omits
--          RLS to match the working production state.
-- ============================================================================

-- ═════════════════════════════════════════════════════════════════════════════
-- 1. ENUM TYPES
-- ═════════════════════════════════════════════════════════════════════════════

DO $$ BEGIN
  CREATE TYPE public.payment_mode_type AS ENUM ('Cash', 'UPI', 'PhonePe/GPay');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE public.payment_type_type AS ENUM ('Full', 'Partial');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;


-- ═════════════════════════════════════════════════════════════════════════════
-- 2. TABLES (alphabetical — FKs after tables they reference)
-- ═════════════════════════════════════════════════════════════════════════════

-- ── users (base table, no FKs) ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.users (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firstname     character varying(250) NOT NULL,
  lastname      character varying(250) NOT NULL,
  username      character varying(100) NOT NULL,
  password      character varying(255) NOT NULL,
  avatar        text,
  last_login    timestamp with time zone,
  type          smallint NOT NULL DEFAULT 0,
  mechanic_id   integer,
  date_added    timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  date_updated  timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ── profiles (FK → auth.users) ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.profiles (
  id            uuid NOT NULL PRIMARY KEY,
  full_name     text,
  role          text DEFAULT 'staff',
  avatar_url    text,
  updated_at    timestamp with time zone DEFAULT now(),
  mechanic_id   bigint,
  email         text,
  date_updated  timestamp with time zone DEFAULT now(),
  client_id     bigint
);

-- ── client_list ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.client_list (
  id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firstname           text NOT NULL,
  middlename          text,
  lastname            text NOT NULL,
  contact             character varying(100) NOT NULL,
  email               text,
  address             text NOT NULL,
  image_path          text,
  opening_balance     numeric DEFAULT 0,
  delete_flag         smallint NOT NULL DEFAULT 0,
  date_created        timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  date_updated        timestamp without time zone,
  payment_due_date    date,
  payment_due_remarks text,
  login_allowed       boolean NOT NULL DEFAULT false
);

-- ── mechanic_list ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.mechanic_list (
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firstname            character varying(250) NOT NULL,
  middlename           text,
  lastname             character varying(250) NOT NULL,
  contact              character varying(50) NOT NULL,
  designation          character varying(100) DEFAULT 'Mechanic',
  daily_salary         numeric DEFAULT 0,
  avatar               character varying(255) DEFAULT 'default-avatar.jpg',
  commission_percent   numeric DEFAULT 0,
  status               smallint NOT NULL DEFAULT 1,
  delete_flag          smallint NOT NULL DEFAULT 0,
  date_added           timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  date_updated         timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  salary_per_day       numeric NOT NULL DEFAULT 0,
  image_path           text
);

-- ── suppliers ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.suppliers (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text NOT NULL DEFAULT '',
  contact       text NOT NULL DEFAULT '',
  email         text NOT NULL DEFAULT '',
  address       text NOT NULL DEFAULT '',
  status        bigint NOT NULL DEFAULT 1,
  delete_flag   bigint NOT NULL DEFAULT 0,
  date_created  timestamp with time zone NOT NULL DEFAULT now(),
  date_updated  timestamp with time zone NOT NULL DEFAULT now()
);

-- ── spare_supplier (junction) ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.spare_supplier (
  spare_id    bigint NOT NULL,
  supplier_id bigint NOT NULL,
  PRIMARY KEY (spare_id, supplier_id)
);

-- ── service_list ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.service_list (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text NOT NULL,
  description   text NOT NULL,
  price         numeric NOT NULL DEFAULT 0,
  status        smallint NOT NULL DEFAULT 1,
  delete_flag   smallint NOT NULL DEFAULT 0,
  date_created  timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  date_updated  timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  hsn           character varying(20) NOT NULL DEFAULT ''
);

-- ── product_list ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.product_list (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            text NOT NULL,
  description     text NOT NULL,
  cost_price      numeric NOT NULL DEFAULT 0,
  price           numeric NOT NULL DEFAULT 0,
  image_path      text NOT NULL,
  status          smallint NOT NULL DEFAULT 1,
  delete_flag     smallint NOT NULL DEFAULT 0,
  date_created    timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  date_updated    timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  hsn             character varying(20) NOT NULL DEFAULT '',
  alert_quantity  integer NOT NULL DEFAULT 0,
  barcode         character varying(100) DEFAULT NULL,
  place_zone      text,
  place_rack      text,
  place_bin       text,
  place_box       text
);

-- ── transaction_list ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.transaction_list (
  id                            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                       integer NOT NULL,
  mechanic_id                   integer,
  code                          character varying(100) NOT NULL,
  job_id                        character varying(20) DEFAULT NULL,
  client_name                   text,
  fault                         text NOT NULL,
  remark                        text NOT NULL,
  item                          text NOT NULL,
  uniq_id                       text NOT NULL,
  amount                        numeric NOT NULL DEFAULT 0,
  mechanic_amount               numeric NOT NULL DEFAULT 0,
  mechanic_commission_amount    numeric DEFAULT 0,
  del_status                    smallint NOT NULL DEFAULT 0,
  status                        smallint NOT NULL DEFAULT 0,
  date_created                  timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  date_updated                  timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  date_completed                timestamp with time zone
);

-- ── transaction_products ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.transaction_products (
  transaction_id  integer NOT NULL,
  product_id      integer NOT NULL,
  product_name    text,
  qty             integer NOT NULL DEFAULT 0,
  price           numeric NOT NULL DEFAULT 0,
  PRIMARY KEY (transaction_id, product_id)
);

-- ── transaction_services ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.transaction_services (
  transaction_id  integer NOT NULL,
  service_id      integer NOT NULL,
  service_name    text,
  price           numeric NOT NULL DEFAULT 0,
  PRIMARY KEY (transaction_id, service_id)
);

-- ── transaction_images ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.transaction_images (
  id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id    integer NOT NULL,
  image_path        character varying(255) NOT NULL,
  date_created      timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ── inventory_list ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.inventory_list (
  id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id          integer NOT NULL,
  quantity            integer NOT NULL DEFAULT 0,
  place               text,
  stock_date          date NOT NULL,
  date_created        timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  date_updated        timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  supplier_id         bigint,
  purchase_cost       numeric NOT NULL DEFAULT 0,
  courier_charges     numeric NOT NULL DEFAULT 0,
  place_zone          text,
  place_rack          text,
  place_bin           text,
  place_box           text,
  purchase_order_id   integer
);

-- ── client_payments ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.client_payments (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id       integer NOT NULL,
  job_id          character varying(50) DEFAULT NULL,
  loan_id         integer,
  bill_no         character varying(50) DEFAULT NULL,
  payment_date    date DEFAULT CURRENT_DATE,
  amount          numeric NOT NULL,
  discount        numeric DEFAULT 0,
  net_amount      numeric,
  payment_mode    public.payment_mode_type DEFAULT 'Cash',
  payment_type    public.payment_type_type DEFAULT 'Full',
  remarks         text,
  created_at      timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- ── client_loans ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.client_loans (
  id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id         integer NOT NULL,
  principal_amount  numeric NOT NULL,
  interest_rate     numeric DEFAULT 0,
  loan_period       integer NOT NULL,
  total_payable     numeric NOT NULL,
  emi_amount        numeric NOT NULL,
  remarks           text,
  loan_date         date NOT NULL,
  status            smallint DEFAULT 1,
  created_at        timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- ── direct_sales ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.direct_sales (
  id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_code           character varying(100) NOT NULL,
  client_id           integer,
  mechanic_id         integer,
  total_amount        numeric NOT NULL,
  payment_mode        character varying(50) NOT NULL,
  remarks             text,
  last_edited_by      integer,
  last_edited_by_name character varying(100) DEFAULT NULL,
  last_edited_date    timestamp without time zone,
  date_created        timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ── direct_sale_items ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.direct_sale_items (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id     integer NOT NULL,
  product_id  integer NOT NULL,
  qty         integer NOT NULL,
  price       numeric NOT NULL
);

-- ── job_id_counter ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.job_id_counter (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  last_job_id   integer DEFAULT 0
);

-- ── expense_list ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.expense_list (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category      character varying(200) NOT NULL,
  amount        numeric NOT NULL DEFAULT 0,
  remarks       text,
  date_created  timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ── system_info ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.system_info (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meta_field  text NOT NULL,
  meta_value  text NOT NULL
);

-- ── activity_logs ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.activity_logs (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       integer,
  action        text,
  module        text,
  meta_id       text,
  details       text,
  date_created  timestamp with time zone DEFAULT now()
);

-- ── attendance_list ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.attendance_list (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mechanic_id   integer NOT NULL,
  status        smallint NOT NULL DEFAULT 0,
  curr_date     date NOT NULL,
  time_in       time without time zone,
  time_out      time without time zone,
  lat_in        double precision,
  lng_in        double precision,
  lat_out       double precision,
  lng_out       double precision
);

-- ── advance_payments ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.advance_payments (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mechanic_id   integer NOT NULL,
  amount        numeric NOT NULL DEFAULT 0,
  date_paid     date NOT NULL,
  reason        text,
  date_created  timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ── mechanic_salary_history ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.mechanic_salary_history (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mechanic_id     integer NOT NULL,
  salary          numeric NOT NULL DEFAULT 0,
  effective_date  date NOT NULL,
  date_created    timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ── mechanic_commission_history ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.mechanic_commission_history (
  id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mechanic_id         integer NOT NULL,
  commission_percent  numeric NOT NULL,
  effective_date      date NOT NULL,
  date_created        timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ── lender_list ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.lender_list (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fullname        character varying(250) NOT NULL,
  contact         character varying(20) NOT NULL,
  loan_amount     numeric NOT NULL DEFAULT 0,
  interest_rate   numeric NOT NULL DEFAULT 0,
  tenure_months   integer NOT NULL DEFAULT 0,
  reason          text,
  emi_amount      numeric NOT NULL DEFAULT 0,
  start_date      date NOT NULL,
  status          smallint NOT NULL DEFAULT 1,
  date_created    timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ── loan_payments ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.loan_payments (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lender_id     integer NOT NULL,
  amount_paid   double precision NOT NULL DEFAULT 0,
  payment_date  date NOT NULL,
  remarks       text
);

-- ── message_list ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.message_list (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fullname      text NOT NULL,
  contact       text NOT NULL,
  email         text NOT NULL,
  message       text NOT NULL,
  status        smallint NOT NULL DEFAULT 0,
  date_created  timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ── payment_reminders ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.payment_reminders (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id       bigint NOT NULL,
  amount_due      numeric NOT NULL DEFAULT 0,
  reminder_date   timestamp with time zone NOT NULL DEFAULT now(),
  channel         character varying(50) DEFAULT 'System Alert',
  status          character varying(50) DEFAULT 'Sent',
  remarks         text
);

-- ── wp_template_history ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.wp_template_history (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_key  text NOT NULL DEFAULT '',
  action        text NOT NULL DEFAULT '',
  old_value     text,
  new_value     text,
  changed_by    text NOT NULL DEFAULT '',
  changed_at    timestamp with time zone NOT NULL DEFAULT now()
);

-- ── login_throttle ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.login_throttle (
  id                bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email             text NOT NULL,
  ip_address        text NOT NULL,
  attempt_count     integer NOT NULL DEFAULT 0,
  lock_repeats      integer NOT NULL DEFAULT 0,
  first_attempt_at  timestamp with time zone,
  lockout_until     timestamp with time zone,
  last_attempt_at   timestamp with time zone NOT NULL DEFAULT now(),
  updated_at        timestamp with time zone NOT NULL DEFAULT now()
);

-- ── locations ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.locations (
  id          serial PRIMARY KEY,
  zone        text NOT NULL,
  rack        text NOT NULL DEFAULT '',
  bin         text NOT NULL DEFAULT '',
  box         text NOT NULL DEFAULT '',
  label       text,
  status      integer NOT NULL DEFAULT 1,
  delete_flag integer NOT NULL DEFAULT 0,
  created_at  timestamp with time zone DEFAULT now()
);

-- ── product_locations (junction) ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.product_locations (
  product_id  integer NOT NULL,
  location_id integer NOT NULL,
  created_at  timestamp with time zone DEFAULT now(),
  PRIMARY KEY (product_id, location_id)
);

-- ── purchase_orders ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.purchase_orders (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  po_code         text NOT NULL,
  supplier_id     bigint,
  status          text NOT NULL DEFAULT 'pending',
  expected_date   date,
  notes           text DEFAULT '',
  total_amount    numeric(12,2) NOT NULL DEFAULT 0,
  received_date   date,
  date_created    timestamp with time zone NOT NULL DEFAULT now(),
  date_updated    timestamp with time zone NOT NULL DEFAULT now()
);

-- ── purchase_order_items ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.purchase_order_items (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_order_id   bigint NOT NULL,
  product_id          bigint NOT NULL,
  qty_ordered         integer NOT NULL DEFAULT 0,
  qty_received        integer NOT NULL DEFAULT 0,
  unit_cost           numeric(12,2) NOT NULL DEFAULT 0,
  date_created        timestamp with time zone NOT NULL DEFAULT now()
);

-- ── push_subscriptions ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.push_subscriptions (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       uuid,
  endpoint      text NOT NULL,
  p256dh        text NOT NULL DEFAULT '',
  auth          text NOT NULL DEFAULT '',
  device_name   text DEFAULT '',
  enabled       boolean NOT NULL DEFAULT true,
  date_created  timestamp with time zone NOT NULL DEFAULT now(),
  date_updated  timestamp with time zone NOT NULL DEFAULT now()
);


-- ═════════════════════════════════════════════════════════════════════════════
-- 3. ADD MISSING COLUMNS (idempotent — runs on existing tables too)
-- ═════════════════════════════════════════════════════════════════════════════

-- profiles
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS mechanic_id bigint;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS client_id bigint;

-- mechanic_list
ALTER TABLE public.mechanic_list ADD COLUMN IF NOT EXISTS image_path text DEFAULT NULL;

-- product_list
ALTER TABLE public.product_list ADD COLUMN IF NOT EXISTS place_zone text;
ALTER TABLE public.product_list ADD COLUMN IF NOT EXISTS place_rack text;
ALTER TABLE public.product_list ADD COLUMN IF NOT EXISTS place_bin text;
ALTER TABLE public.product_list ADD COLUMN IF NOT EXISTS place_box text;

-- inventory_list
ALTER TABLE public.inventory_list ADD COLUMN IF NOT EXISTS place_zone text;
ALTER TABLE public.inventory_list ADD COLUMN IF NOT EXISTS place_rack text;
ALTER TABLE public.inventory_list ADD COLUMN IF NOT EXISTS place_bin text;
ALTER TABLE public.inventory_list ADD COLUMN IF NOT EXISTS place_box text;
ALTER TABLE public.inventory_list ADD COLUMN IF NOT EXISTS purchase_order_id integer;
ALTER TABLE public.inventory_list ALTER COLUMN place DROP NOT NULL;

-- locations
ALTER TABLE public.locations ADD COLUMN IF NOT EXISTS delete_flag integer NOT NULL DEFAULT 0;
ALTER TABLE public.locations ADD COLUMN IF NOT EXISTS status integer NOT NULL DEFAULT 1;


-- ═════════════════════════════════════════════════════════════════════════════
-- 4. CHECK CONSTRAINTS
-- ═════════════════════════════════════════════════════════════════════════════

-- profiles.role: admin | staff | client | developer
DO $$ BEGIN
  ALTER TABLE public.profiles ADD CONSTRAINT profiles_role_check
    CHECK (role IN ('admin', 'staff', 'client', 'developer'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- purchase_orders.status
DO $$ BEGIN
  ALTER TABLE public.purchase_orders ADD CONSTRAINT purchase_orders_status_check
    CHECK (status IN ('pending', 'ordered', 'received', 'cancelled'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- locations unique zone+rack+bin+box
DO $$ BEGIN
  ALTER TABLE public.locations ADD CONSTRAINT locations_zone_rack_bin_box_uniq
    UNIQUE (zone, rack, bin, box);
EXCEPTION WHEN OTHERS THEN NULL;
END $$;


-- ═════════════════════════════════════════════════════════════════════════════
-- 5. UNIQUE INDEXES
-- ═════════════════════════════════════════════════════════════════════════════

-- profiles: 1:1 mechanic link
CREATE UNIQUE INDEX IF NOT EXISTS profiles_mechanic_id_unique
  ON public.profiles (mechanic_id) WHERE mechanic_id IS NOT NULL;

-- login_throttle: email uniqueness (case-insensitive)
CREATE UNIQUE INDEX IF NOT EXISTS login_throttle_email_uniq
  ON public.login_throttle (lower(email));

-- purchase_orders.po_code uniqueness
DO $$ BEGIN
  ALTER TABLE public.purchase_orders ADD CONSTRAINT purchase_orders_po_code_uniq
    UNIQUE (po_code);
EXCEPTION WHEN OTHERS THEN NULL;
END $$;


-- ═════════════════════════════════════════════════════════════════════════════
-- 6. INDEXES
-- ═════════════════════════════════════════════════════════════════════════════

CREATE INDEX IF NOT EXISTS locations_zone_idx ON public.locations (zone);
CREATE INDEX IF NOT EXISTS product_locations_product_idx ON public.product_locations (product_id);
CREATE INDEX IF NOT EXISTS product_locations_location_idx ON public.product_locations (location_id);
CREATE INDEX IF NOT EXISTS product_list_place_zone_idx ON public.product_list (place_zone);
CREATE INDEX IF NOT EXISTS inventory_list_place_zone_idx ON public.inventory_list (place_zone);
CREATE INDEX IF NOT EXISTS purchase_orders_status_idx ON public.purchase_orders (status);
CREATE INDEX IF NOT EXISTS purchase_orders_supplier_idx ON public.purchase_orders (supplier_id);
CREATE INDEX IF NOT EXISTS purchase_order_items_po_idx ON public.purchase_order_items (purchase_order_id);
CREATE INDEX IF NOT EXISTS purchase_order_items_product_idx ON public.purchase_order_items (product_id);
CREATE INDEX IF NOT EXISTS push_subscriptions_user_idx ON public.push_subscriptions (user_id);
CREATE INDEX IF NOT EXISTS push_subscriptions_enabled_idx ON public.push_subscriptions (enabled);
CREATE INDEX IF NOT EXISTS login_throttle_ip_idx ON public.login_throttle (ip_address);
CREATE INDEX IF NOT EXISTS login_throttle_updated_idx ON public.login_throttle (updated_at);
CREATE INDEX IF NOT EXISTS idx_suppliers_delete_flag ON public.suppliers (delete_flag);
CREATE INDEX IF NOT EXISTS idx_spare_supplier_supplier ON public.spare_supplier (supplier_id);
CREATE INDEX IF NOT EXISTS idx_wpth_template_key ON public.wp_template_history (template_key);
CREATE INDEX IF NOT EXISTS idx_payment_reminders_client ON public.payment_reminders (client_id);


-- ═════════════════════════════════════════════════════════════════════════════
-- 7. FOREIGN KEYS
-- ═════════════════════════════════════════════════════════════════════════════

-- profiles → auth.users
DO $$ BEGIN
  ALTER TABLE public.profiles ADD CONSTRAINT profiles_id_fk
    FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- profiles → client_list
DO $$ BEGIN
  ALTER TABLE public.profiles ADD CONSTRAINT profiles_client_id_fk
    FOREIGN KEY (client_id) REFERENCES public.client_list(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- inventory_list → product_list
DO $$ BEGIN
  ALTER TABLE public.inventory_list ADD CONSTRAINT inventory_product_fk
    FOREIGN KEY (product_id) REFERENCES public.product_list(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- inventory_list → suppliers
DO $$ BEGIN
  ALTER TABLE public.inventory_list ADD CONSTRAINT inventory_supplier_fk
    FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- transaction_products → transaction_list
DO $$ BEGIN
  ALTER TABLE public.transaction_products ADD CONSTRAINT txn_products_txn_fk
    FOREIGN KEY (transaction_id) REFERENCES public.transaction_list(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- transaction_products → product_list
DO $$ BEGIN
  ALTER TABLE public.transaction_products ADD CONSTRAINT txn_products_product_fk
    FOREIGN KEY (product_id) REFERENCES public.product_list(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- transaction_services → transaction_list
DO $$ BEGIN
  ALTER TABLE public.transaction_services ADD CONSTRAINT txn_services_txn_fk
    FOREIGN KEY (transaction_id) REFERENCES public.transaction_list(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- transaction_services → service_list
DO $$ BEGIN
  ALTER TABLE public.transaction_services ADD CONSTRAINT txn_services_service_fk
    FOREIGN KEY (service_id) REFERENCES public.service_list(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- transaction_images → transaction_list
DO $$ BEGIN
  ALTER TABLE public.transaction_images ADD CONSTRAINT txn_images_txn_fk
    FOREIGN KEY (transaction_id) REFERENCES public.transaction_list(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- client_payments → client_list
DO $$ BEGIN
  ALTER TABLE public.client_payments ADD CONSTRAINT cp_client_fk
    FOREIGN KEY (client_id) REFERENCES public.client_list(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- client_payments → client_loans
DO $$ BEGIN
  ALTER TABLE public.client_payments ADD CONSTRAINT cp_loan_fk
    FOREIGN KEY (loan_id) REFERENCES public.client_loans(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- client_loans → client_list
DO $$ BEGIN
  ALTER TABLE public.client_loans ADD CONSTRAINT cl_client_fk
    FOREIGN KEY (client_id) REFERENCES public.client_list(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- direct_sales → client_list
DO $$ BEGIN
  ALTER TABLE public.direct_sales ADD CONSTRAINT ds_client_fk
    FOREIGN KEY (client_id) REFERENCES public.client_list(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- direct_sales → mechanic_list
DO $$ BEGIN
  ALTER TABLE public.direct_sales ADD CONSTRAINT ds_mechanic_fk
    FOREIGN KEY (mechanic_id) REFERENCES public.mechanic_list(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- direct_sale_items → direct_sales
DO $$ BEGIN
  ALTER TABLE public.direct_sale_items ADD CONSTRAINT dsi_sale_fk
    FOREIGN KEY (sale_id) REFERENCES public.direct_sales(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- direct_sale_items → product_list
DO $$ BEGIN
  ALTER TABLE public.direct_sale_items ADD CONSTRAINT dsi_product_fk
    FOREIGN KEY (product_id) REFERENCES public.product_list(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- loan_payments → lender_list
DO $$ BEGIN
  ALTER TABLE public.loan_payments ADD CONSTRAINT lp_lender_fk
    FOREIGN KEY (lender_id) REFERENCES public.lender_list(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- payment_reminders → client_list
DO $$ BEGIN
  ALTER TABLE public.payment_reminders ADD CONSTRAINT pr_client_fk
    FOREIGN KEY (client_id) REFERENCES public.client_list(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- purchase_orders → suppliers
DO $$ BEGIN
  ALTER TABLE public.purchase_orders ADD CONSTRAINT purchase_orders_supplier_fk
    FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- purchase_order_items → purchase_orders
DO $$ BEGIN
  ALTER TABLE public.purchase_order_items ADD CONSTRAINT purchase_order_items_po_fk
    FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- purchase_order_items → product_list
DO $$ BEGIN
  ALTER TABLE public.purchase_order_items ADD CONSTRAINT purchase_order_items_product_fk
    FOREIGN KEY (product_id) REFERENCES public.product_list(id) ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- push_subscriptions → profiles
DO $$ BEGIN
  ALTER TABLE public.push_subscriptions ADD CONSTRAINT push_subscriptions_user_fk
    FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- product_locations → product_list
DO $$ BEGIN
  ALTER TABLE public.product_locations ADD CONSTRAINT pl_product_fk
    FOREIGN KEY (product_id) REFERENCES public.product_list(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- product_locations → locations
DO $$ BEGIN
  ALTER TABLE public.product_locations ADD CONSTRAINT pl_location_fk
    FOREIGN KEY (location_id) REFERENCES public.locations(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;


-- ═════════════════════════════════════════════════════════════════════════════
-- 8. FUNCTIONS
-- ═════════════════════════════════════════════════════════════════════════════

-- prevent_role_escalation
CREATE OR REPLACE FUNCTION public.prevent_role_escalation()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
begin
  if auth.role() in ('anon', 'authenticated') and new.role is distinct from 'staff' then
    raise exception 'Role escalation not allowed';
  end if;
  return new;
end;
$$;

-- touch_purchase_orders
CREATE OR REPLACE FUNCTION public.touch_purchase_orders()
RETURNS trigger
LANGUAGE plpgsql
AS $$
begin
  new.date_updated = now();
  return new;
end;
$$;

-- touch_push_subscriptions
CREATE OR REPLACE FUNCTION public.touch_push_subscriptions()
RETURNS trigger
LANGUAGE plpgsql
AS $$
begin
  new.date_updated = now();
  return new;
end;
$$;


-- ═════════════════════════════════════════════════════════════════════════════
-- 9. TRIGGERS
-- ═════════════════════════════════════════════════════════════════════════════

DROP TRIGGER IF EXISTS prevent_role_escalation_trigger ON public.profiles;
CREATE TRIGGER prevent_role_escalation_trigger
  BEFORE INSERT OR UPDATE OF role ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.prevent_role_escalation();

DROP TRIGGER IF EXISTS purchase_orders_touch ON public.purchase_orders;
CREATE TRIGGER purchase_orders_touch
  BEFORE UPDATE ON public.purchase_orders
  FOR EACH ROW EXECUTE FUNCTION public.touch_purchase_orders();

DROP TRIGGER IF EXISTS push_subscriptions_touch ON public.push_subscriptions;
CREATE TRIGGER push_subscriptions_touch
  BEFORE UPDATE ON public.push_subscriptions
  FOR EACH ROW EXECUTE FUNCTION public.touch_push_subscriptions();


-- ═════════════════════════════════════════════════════════════════════════════
-- 10. SEED DATA
-- ═════════════════════════════════════════════════════════════════════════════

-- job_id_counter seed (idempotent)
INSERT INTO public.job_id_counter (id, last_job_id)
SELECT 1, greatest(
  coalesce(
    (select max(case when job_id ~ '^[0-9]+$' then job_id::bigint end) from public.transaction_list),
    0
  ),
  28101
)
WHERE NOT EXISTS (SELECT 1 FROM public.job_id_counter WHERE id = 1);

-- system_info seed (idempotent) — core business defaults
INSERT INTO public.system_info (meta_field, meta_value)
VALUES
  ('owner', ''),
  ('geofence_enabled', 'false'),
  ('geofence_lat', '0'),
  ('geofence_lng', '0'),
  ('geofence_radius_m', '100'),
  ('name', 'V-Technologies'),
  ('short_name', 'V-Tech'),
  ('email', ''),
  ('contact', ''),
  ('address', ''),
  ('logo', ''),
  ('cover', ''),
  ('gst_no', ''),
  ('gstin', ''),
  ('biz_days', 'Mon-Sat'),
  ('biz_open', '10:00'),
  ('biz_close', '20:00'),
  ('map_url', ''),
  ('map_iframe', ''),
  ('whatsapp', ''),
  ('facebook', ''),
  ('instagram', ''),
  ('youtube', ''),
  ('footer_text', ''),
  ('announcement', ''),
  ('upi_id', ''),
  ('ai_provider', 'groq'),
  ('ai_model', 'llama-3.3-70b-versatile'),
  ('ai_api_key', ''),
  ('license_key', ''),
  ('license_status', '{"activated":false}'),
  ('license_last_checked', ''),
  ('log_retention', '90'),
  ('whatsapp_welcome', ''),
  ('whatsapp_reminder', ''),
  ('whatsapp_followup', ''),
  ('whatsapp_offer', ''),
  ('whatsapp_greeting', ''),
  ('whatsapp_sale', ''),
  ('whatsapp_status_pending', ''),
  ('whatsapp_status_repairing', ''),
  ('whatsapp_status_ready', ''),
  ('whatsapp_status_delivered', ''),
  ('whatsapp_status_cancelled', ''),
  ('csrf_token', ''),
  ('signature', ''),
  ('signature_canvas', ''),
  ('delete_signature', '0')
ON CONFLICT DO NOTHING;


-- ═════════════════════════════════════════════════════════════════════════════
-- 11. STORAGE BUCKETS
-- ═════════════════════════════════════════════════════════════════════════════

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES
  ('client-photos',  'client-photos',  true, 1048576, ARRAY['image/jpeg','image/png','image/webp']),
  ('job-images',     'job-images',     true, 1048576, ARRAY['image/jpeg','image/png','image/webp']),
  ('mechanic-photos','mechanic-photos', true, 1048576, ARRAY['image/jpeg','image/png','image/webp']),
  ('user-avatars',   'user-avatars',   true, 1048576, ARRAY['image/jpeg','image/png','image/webp']),
  ('product-images', 'product-images', true, 1048576, ARRAY['image/jpeg','image/png','image/webp'])
ON CONFLICT (id) DO NOTHING;


-- ═════════════════════════════════════════════════════════════════════════════
-- 12. DROP AUTO-CREATE TRIGGER (profiles no longer auto-created)
-- ═════════════════════════════════════════════════════════════════════════════

DO $$ DECLARE t record; BEGIN
  FOR t IN
    SELECT tgname FROM pg_trigger
    WHERE tgrelid = 'auth.users'::regclass
      AND tgname IN ('on_auth_user_created', 'handle_new_user_trigger', 'auth_user_created')
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS %I ON auth.users', t.tgname);
    RAISE NOTICE 'dropped trigger %', t.tgname;
  END LOOP;
END $$;


-- ═════════════════════════════════════════════════════════════════════════════
-- DONE
-- ═════════════════════════════════════════════════════════════════════════════

NOTIFY pgrst, 'reload schema';
