-- ═══════════════════════════════════════════════════════════════════════════
-- I2 — STOCKTAKE & STOCK ADJUSTMENT (isolated additive migration)
-- ---------------------------------------------------------------------------
-- Goals (per docs/plans/inventory_improvements_plan.md §2 / I2):
--   * Physical stock-count capture (staff).
--   * System correction WITHOUT deleting history:
--       derived available = Σ inventory_list.quantity − Σ job qty − Σ sale qty
--     So a correction = inserting a +/− QTY reconciliation row into
--     inventory_list (negative allowed — no CHECK on quantity).
--   * Full audit trail in stock_adjustments (reason ⊂ {shrinkage,damage,
--     correction,return}) + stock_counts header (physical count snapshot).
--
-- Delivery rule (lock by user): NEW isolated file ONLY — do NOT edit
--   the consolidated 20260913_final_full_schema_idempotent.sql.
--
-- Idempotent + re-run safe + zero data loss. Same composite pattern as the
-- consolidated file (CREATE IF NOT EXISTS + guarded DO add-column + guarded
-- identity + guarded PK/FK + DROP→CREATE policy + guarded index + grants).
-- ═══════════════════════════════════════════════════════════════════════════

-- ── 1. Tables ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.stock_counts (
    id bigint NOT NULL,
    product_id integer NOT NULL,
    counted_qty integer NOT NULL,
    counted_at timestamptz DEFAULT now(),
    counted_by uuid,
    note text,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.stock_adjustments (
    id bigint NOT NULL,
    product_id integer NOT NULL,
    delta integer NOT NULL,
    reason text NOT NULL,
    remark text,
    created_at timestamptz DEFAULT now(),
    created_by uuid,
    inventory_list_id integer
);

-- ── 2. Guarded column adds (table may pre-date this migration) ─────────────
do $$ begin
  alter table public.stock_counts add column if not exists id bigint;
  alter table public.stock_counts add column if not exists product_id integer;
  alter table public.stock_counts add column if not exists counted_qty integer;
  alter table public.stock_counts add column if not exists counted_at timestamptz DEFAULT now();
  alter table public.stock_counts add column if not exists counted_by uuid;
  alter table public.stock_counts add column if not exists note text;
  alter table public.stock_counts add column if not exists created_at timestamptz DEFAULT now();
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='stock_counts' and column_name='id' and is_nullable='YES') then
    alter table public.stock_counts alter column id set not null;
  end if;
exception when duplicate_column then null; end $$;

do $$ begin
  alter table public.stock_adjustments add column if not exists id bigint;
  alter table public.stock_adjustments add column if not exists product_id integer;
  alter table public.stock_adjustments add column if not exists delta integer;
  alter table public.stock_adjustments add column if not exists reason text;
  alter table public.stock_adjustments add column if not exists remark text;
  alter table public.stock_adjustments add column if not exists created_at timestamptz DEFAULT now();
  alter table public.stock_adjustments add column if not exists created_by uuid;
  alter table public.stock_adjustments add column if not exists inventory_list_id integer;
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='stock_adjustments' and column_name='id' and is_nullable='YES') then
    alter table public.stock_adjustments alter column id set not null;
  end if;
exception when duplicate_column then null; end $$;

-- ── 3. Identity (id auto-increment) ────────────────────────────────────────
do $$ begin
  if not exists (select 1 from pg_attribute a where a.attrelid='public.stock_counts'::regclass and a.attname='id' and a.attidentity<>'') then
    alter table public.stock_counts alter column id add generated by default as identity;
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_attribute a where a.attrelid='public.stock_adjustments'::regclass and a.attname='id' and a.attidentity<>'') then
    alter table public.stock_adjustments alter column id add generated by default as identity;
  end if;
end $$;

-- ── 4. RLS — enable on fresh tables ────────────────────────────────────────
ALTER TABLE public.stock_counts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_adjustments ENABLE ROW LEVEL SECURITY;

-- ── 5. Primary keys + checks (guarded) ────────────────────────────────────
do $$ begin if not exists (select 1 from pg_constraint where conname='stock_counts_pkey' and conrelid='public.stock_counts'::regclass) then alter table only public.stock_counts add constraint stock_counts_pkey primary key (id); end if; end $$;
do $$ begin if not exists (select 1 from pg_constraint where conname='stock_adjustments_pkey' and conrelid='public.stock_adjustments'::regclass) then alter table only public.stock_adjustments add constraint stock_adjustments_pkey primary key (id); end if; end $$;
do $$ begin if not exists (select 1 from pg_constraint where conname='stock_adjustments_reason_check' and conrelid='public.stock_adjustments'::regclass) then alter table only public.stock_adjustments add constraint stock_adjustments_reason_check check ((reason in ('shrinkage'::text, 'damage'::text, 'correction'::text, 'return'::text))); end if; end $$;

-- ── 6. Foreign keys (guarded) ─────────────────────────────────────────────
do $$ begin if not exists (select 1 from pg_constraint where conname='stock_counts_product_id_fkey' and conrelid='public.stock_counts'::regclass) then alter table only public.stock_counts add constraint stock_counts_product_id_fkey foreign key (product_id) references public.product_list(id) on delete cascade; end if; end $$;
do $$ begin if not exists (select 1 from pg_constraint where conname='stock_counts_counted_by_fkey' and conrelid='public.stock_counts'::regclass) then alter table only public.stock_counts add constraint stock_counts_counted_by_fkey foreign key (counted_by) references public.profiles(id) on delete set null; end if; end $$;
do $$ begin if not exists (select 1 from pg_constraint where conname='stock_adjustments_product_id_fkey' and conrelid='public.stock_adjustments'::regclass) then alter table only public.stock_adjustments add constraint stock_adjustments_product_id_fkey foreign key (product_id) references public.product_list(id) on delete cascade; end if; end $$;
do $$ begin if not exists (select 1 from pg_constraint where conname='stock_adjustments_created_by_fkey' and conrelid='public.stock_adjustments'::regclass) then alter table only public.stock_adjustments add constraint stock_adjustments_created_by_fkey foreign key (created_by) references public.profiles(id) on delete set null; end if; end $$;
do $$ begin if not exists (select 1 from pg_constraint where conname='stock_adjustments_inventory_list_id_fkey' and conrelid='public.stock_adjustments'::regclass) then alter table only public.stock_adjustments add constraint stock_adjustments_inventory_list_id_fkey foreign key (inventory_list_id) references public.inventory_list(id) on delete set null; end if; end $$;

-- ── 7. RLS policies — staff-only (anon = 0), DROP→CREATE ──────────────────
DROP POLICY IF EXISTS rlslock_stock_counts_staff ON public.stock_counts;
CREATE POLICY rlslock_stock_counts_staff ON public.stock_counts TO authenticated USING (public.is_frontend_staff()) WITH CHECK (public.is_frontend_staff());

DROP POLICY IF EXISTS rlslock_stock_adjustments_staff ON public.stock_adjustments;
CREATE POLICY rlslock_stock_adjustments_staff ON public.stock_adjustments TO authenticated USING (public.is_frontend_staff()) WITH CHECK (public.is_frontend_staff());

-- ── 8. Indexes (guarded) ──────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS stock_counts_product_created_idx ON public.stock_counts USING btree (product_id, counted_at);
CREATE INDEX IF NOT EXISTS stock_adjustments_product_created_idx ON public.stock_adjustments USING btree (product_id, created_at);

-- ── 9. Atomic writer RPC: record_stocktake ────────────────────────────────
-- SECURITY DEFINER + staff-check so one transaction writes the reconciliation
-- row AND both ledger tables atomically (no client-side partial failure).
CREATE OR REPLACE FUNCTION public.record_stocktake(
    p_product_id integer,
    p_counted_qty integer,
    p_reason text DEFAULT 'correction',
    p_note text DEFAULT NULL,
    p_remark text DEFAULT NULL,
    p_place text DEFAULT NULL
) RETURNS TABLE(
    adjustment_id bigint,
    inventory_list_id integer,
    available_before bigint,
    delta integer
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
declare
    v_available bigint;
    v_delta integer;
    v_inv_id integer;
    v_adj_id bigint;
begin
    if not public.is_frontend_staff() then
        raise exception 'permission denied: staff only';
    end if;

    if p_counted_qty is null then
        raise exception 'counted_qty is required';
    end if;
    if p_reason is null or p_reason not in ('shrinkage','damage','correction','return') then
        raise exception 'invalid reason: %', coalesce(p_reason, '<null>');
    end if;
    if p_product_id is null then
        raise exception 'product_id is required';
    end if;

    -- live derived available from the single-source RPC (I1 formula)
    select available into v_available
      from public.get_inventory_stock(array[p_product_id]::int8[])
      where product_id = p_product_id;
    if v_available is null then
        v_available := 0;
    end if;

    v_delta := p_counted_qty - v_available;

    -- reconciliation row (delta may be negative; quantity has no CHECK here)
    insert into public.inventory_list
        (product_id, quantity, stock_date, purchase_cost, place, date_created, date_updated)
    values
        (p_product_id, v_delta, current_date, 0, p_place, now(), now())
    returning id into v_inv_id;

    -- audit ledger
    insert into public.stock_adjustments
        (product_id, delta, reason, remark, created_by, inventory_list_id)
    values
        (p_product_id, v_delta, p_reason, p_remark, auth.uid(), v_inv_id)
    returning id into v_adj_id;

    -- physical-count header
    insert into public.stock_counts
        (product_id, counted_qty, counted_by, note)
    values
        (p_product_id, p_counted_qty, auth.uid(), p_note);

    return query select v_adj_id::bigint, v_inv_id, v_available, v_delta;
end;
$$;

REVOKE ALL ON FUNCTION public.record_stocktake(integer, integer, text, text, text, text) FROM public;
GRANT EXECUTE ON FUNCTION public.record_stocktake(integer, integer, text, text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.record_stocktake(integer, integer, text, text, text, text) TO service_role;

-- ── 10. Store-level grants (match repo: ALL to anon/auth/service) ──────────
GRANT ALL ON TABLE public.stock_counts TO anon;
GRANT ALL ON TABLE public.stock_counts TO authenticated;
GRANT ALL ON TABLE public.stock_counts TO service_role;
GRANT ALL ON TABLE public.stock_adjustments TO anon;
GRANT ALL ON TABLE public.stock_adjustments TO authenticated;
GRANT ALL ON TABLE public.stock_adjustments TO service_role;

-- ═══════════════════════════════════════════════════════════════════════════