-- ════════════════════════════════════════════════════════════════════════
-- 20260922_bom_templates.sql
-- BOM Checker — SAVED TEMPLATES (bom_checker_plan.md Phase 3)
--
--  `bom_templates` — reusable component lists, technician saved:
--    • name         — template title (required)
--    • description  — optional note
--    • items        — jsonb, [{ product_id, name, qty, notes }]
--                       (product_id nullable — product deleted ho to bhi
--                        text restore + stale-warning possible)
--    • created_by   — profiles.id (nullable, set null on profile delete)
--
-- Follows repo conventions (20260921_client_contacts.sql mirror):
--   • bigint identity PK, guard-style idempotent constraints
--   • RLS: `rlslock_*_staff` (is_frontend_staff() gate)
--   • grants anon/authenticated/service_role + sequence grants
--   • touch trigger (updated_at)
--   • idempotent: baar baar run safe
--
-- Apply: Supabase SQL Editor me run karo (ek baar). Verify:
--   select relname from pg_class
--   where relnamespace='public'::regnamespace and relname='bom_templates';
-- ════════════════════════════════════════════════════════════════════════

-- ── 1) bom_templates ───────────────────────────────────────────────────
create table if not exists public.bom_templates (
  id            bigint generated by default as identity,
  name          text not null,
  description   text not null default '',
  items         jsonb not null default '[]'::jsonb,
  created_by    uuid,
  date_created  timestamptz not null default now(),
  date_updated  timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'bom_templates_pkey'
      and conrelid = 'public.bom_templates'::regclass
  ) then
    alter table only public.bom_templates
      add constraint bom_templates_pkey primary key (id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'bom_templates_creator_fk'
      and conrelid = 'public.bom_templates'::regclass
  ) then
    alter table only public.bom_templates
      add constraint bom_templates_creator_fk
      foreign key (created_by) references public.profiles(id)
      on delete set null;
  end if;
end $$;

create index if not exists bom_templates_name_idx
  on public.bom_templates(name);

create index if not exists bom_templates_creator_idx
  on public.bom_templates(created_by);

-- ── 2) touch trigger — bom_templates.date_updated ──────────────────────
create or replace function public.touch_bom_templates()
returns trigger language plpgsql as $$
begin
  new.date_updated = now();
  return new;
end;
$$;

drop trigger if exists bom_templates_touch on public.bom_templates;
create trigger bom_templates_touch
  before update on public.bom_templates
  for each row execute function public.touch_bom_templates();

-- ── 3) RLS — is_frontend_staff() gate (repo pattern) ───────────────────
alter table public.bom_templates enable row level security;

drop policy if exists rlslock_bom_templates_staff on public.bom_templates;
create policy rlslock_bom_templates_staff on public.bom_templates
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

grant all on table public.bom_templates to anon;
grant all on table public.bom_templates to authenticated;
grant all on table public.bom_templates to service_role;
grant usage on sequence public.bom_templates_id_seq to anon, authenticated, service_role;

-- ── 4) Reload PostgREST schema cache ─────────────────────────────────────
NOTIFY pgrst, 'reload schema';

-- ── 5) Report ────────────────────────────────────────────────────────────
select table_name, column_name, data_type, is_nullable
from information_schema.columns
where table_schema = 'public'
  and table_name = 'bom_templates'
order by ordinal_position;