-- ════════════════════════════════════════════════════════════════════════
-- 20260912_supplier_payments.sql
-- Supplier payment / dues ledger (P0 of suppliers_module_plan.md).
--
--   1. `supplier_payments` — har supplier ko diya gaya payment record.
--      Ab tak paid-money ka koi record nahi tha; outstanding balance =
--      Σ PO total_amount − Σ payments, ab track ho sakta hai.
--
-- Follows docs/DATA_MIGRATION_NOTES.md:
--   • bigint identity PK
--   • FK payment → suppliers ON DELETE CASCADE (owned-by)
--   • RLS: `rlslock_supplier_payments_staff` (is_frontend_staff() gate)
--   • grants anon/authenticated/service_role (existing repo pattern)
--   • koi column rename nahi, koi composite PK nahi
--
-- Apply: Supabase SQL Editor me run karo (idempotent, ek baar). Verify:
--   select relname, relrowsecurity from pg_class
--   where relnamespace='public'::regnamespace and relname='supplier_payments';
-- ════════════════════════════════════════════════════════════════════════

-- ── 1) Table ────────────────────────────────────────────────────────────
create table if not exists public.supplier_payments (
  id            bigint generated by default as identity,           -- PK (conname guard below)
  supplier_id   bigint not null references public.suppliers(id) on delete cascade,
  amount        numeric(12,2) not null check (amount > 0),
  payment_mode  text not null default 'cash'
                check (payment_mode in ('cash', 'upi', 'bank_transfer', 'cheque', 'adjustment')),
  reference     text,                                              -- UPI ref, cheque no, txn id
  notes         text,
  payment_date  date not null default current_date,
  created_by    integer,                                           -- transaction_list.user_id mapping
  date_created  timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'supplier_payments_pkey'
      and conrelid = 'public.supplier_payments'::regclass
  ) then
    alter table only public.supplier_payments
      add constraint supplier_payments_pkey primary key (id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'supplier_payments_amount_check'
      and conrelid = 'public.supplier_payments'::regclass
  ) then
    alter table only public.supplier_payments
      add constraint supplier_payments_amount_check check (amount > 0);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'supplier_payments_mode_check'
      and conrelid = 'public.supplier_payments'::regclass
  ) then
    alter table only public.supplier_payments
      add constraint supplier_payments_mode_check
      check (payment_mode in ('cash', 'upi', 'bank_transfer', 'cheque', 'adjustment'));
  end if;
end $$;

create index if not exists supplier_payments_supplier_idx on public.supplier_payments(supplier_id);
create index if not exists supplier_payments_date_idx     on public.supplier_payments(payment_date desc);

-- ── 2) RLS — is_frontend_staff() gate (20260912 pattern) ────────────────
alter table public.supplier_payments enable row level security;

drop policy if exists rlslock_supplier_payments_staff on public.supplier_payments;
create policy rlslock_supplier_payments_staff on public.supplier_payments
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

grant all on table public.supplier_payments to anon;
grant all on table public.supplier_payments to authenticated;
grant all on table public.supplier_payments to service_role;
grant usage on sequence public.supplier_payments_id_seq to anon, authenticated, service_role;

-- ── 3) Reload PostgREST schema cache ─────────────────────────────────────
NOTIFY pgrst, 'reload schema';

-- ── 4) Report ────────────────────────────────────────────────────────────
select column_name, data_type, is_nullable
from information_schema.columns
where table_schema = 'public' and table_name = 'supplier_payments'
order by ordinal_position;