-- ════════════════════════════════════════════════════════════════════════
-- 20260905_job_required_parts.sql
-- Job "Required Spare / Waiting for Part Purchase" tracking.
--
-- Backs docs/plans/job_required_parts_waiting_tracking.md.
--
-- What it does:
--   1. `job_required_parts`  — per-job required-spare entries (which item,
--      qty, kahan se mangwana/source+phone, ETA, photo URL, status 0/1/2).
--   2. `transaction_products.product_id` → nullable — billing me custom
--      (non-inventory) spare daal sakein (product_id NULL, name in
--      product_name). Legacy rows untouched; stock math product_id se key
--      karti hai isliye NULL row ka impact zero hai.
--      NOTE (fix for 42P16): product_id composite PK (transaction_id,
--      product_id) ka hissa tha → PK ko surrogate `id` column par shift kiya
--      (nullable hone ke liye); partial unique index purani uniqueness bachata
--      hai. 20260913000000_final_full_schema_idempotent.sql PK ko conname
--      guard (`transaction_products_pkey`) se re-add karta hai isliye naam
--      change nahi kiya.
--   3. `spare-photos` storage bucket (public read, staff-API writes).
--   4. RLS: `is_frontend_staff()` gate (20260912 pattern) — authenticated only.
--
-- Apply: Supabase SQL Editor me run karo (idempotent, ek baar). Verify:
--   select relname, relrowsecurity from pg_class
--   where relnamespace='public'::regnamespace and relname='job_required_parts';
--
-- Data conventions (docs/DATA_MIGRATION_NOTES.md):
--   • transaction_id = canonical PK `transaction_list.id` (kabhi job_id string nahi)
--   • date_created = waiting-start; date_updated kabhi display mat karo
--   • Job ka "waiting" signal DERIVED hota hai (status<2 row + status in 0..3)
-- ════════════════════════════════════════════════════════════════════════

-- ── 1) Required-parts table ──────────────────────────────────────────────
create table if not exists public.job_required_parts (
  id             bigint generated by default as identity primary key,
  transaction_id integer not null references public.transaction_list(id) on delete cascade,
  product_id     integer references public.product_list(id) on delete set null,
  product_name   text not null default '',
  qty_needed     integer not null default 1,
  qty_received   integer not null default 0,
  status         smallint not null default 0
                 check (status in (0, 1, 2)),     -- 0 waiting | 1 ordered | 2 arrived
  supplier_id    bigint references public.suppliers(id) on delete set null,
  source_name    text,                            -- kahan se mangwana (free text)
  phone          text,
  eta            date,                            -- expected arrival (kab tak)
  photo_url      text,                            -- spare photo (public URL)
  remark         text,
  created_by     integer,
  date_created   timestamptz not null default now(),
  date_updated   timestamptz not null default now(),
  constraint job_required_parts_qty_check check (qty_needed > 0 and qty_received >= 0),
  constraint job_required_parts_arrived_check check (status <> 2 or qty_received >= qty_needed)
);

create index if not exists jrp_transaction_idx  on public.job_required_parts(transaction_id);
create index if not exists jrp_product_idx      on public.job_required_parts(product_id);
create index if not exists jrp_open_idx         on public.job_required_parts(status) where status < 2;

-- date_updated auto-fresh (mehfil me har table same pattern)
drop trigger if exists update_jrp_timestamp on public.job_required_parts;
create trigger update_jrp_timestamp before update on public.job_required_parts
  for each row execute function extensions.moddatetime('date_updated');

-- ── 2) Legacy alter — custom (non-inventory) spare in billing me NULL id ─
-- transaction_products ka PK `transaction_products_pkey (transaction_id,
-- product_id)` hai; product_id PK-column hai isliye seedha `drop not null`
-- se PostgreSQL 42P16 error deta hai. Idhar:
--   a. composite PK drop
--   b. product_id → nullable
--   c. surrogate `id` column + usi par PK (row identity milegi; PostgREST
--      nested join bhi ab possible — pehle composite PK ki wajah se fail hota)
--   d. partial unique index (transaction_id, product_id) WHERE product_id IS
--      NOT NULL — inventory items ki purani uniqueness waise hi bachti hai.
-- Rerun-safe: sab guards ke saath.
alter table public.transaction_products drop constraint if exists transaction_products_pkey;
alter table public.transaction_products alter column product_id drop not null;
alter table public.transaction_products add column if not exists id bigint generated by default as identity;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'transaction_products_pkey'
      and conrelid = 'public.transaction_products'::regclass
  ) then
    alter table only public.transaction_products
      add constraint transaction_products_pkey primary key (id);
  end if;
end $$;

create unique index if not exists transaction_products_inventory_uniq
  on public.transaction_products (transaction_id, product_id)
  where product_id is not null;

-- ── 3) Storage bucket ────────────────────────────────────────────────────
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('spare-photos', 'spare-photos', true, 1048576, array['image/jpeg','image/png','image/webp'])
on conflict (id) do nothing;

-- ── 4) RLS — is_frontend_staff() gate ────────────────────────────────────
alter table public.job_required_parts enable row level security;

drop policy if exists rlslock_jrp_staff on public.job_required_parts;
create policy rlslock_jrp_staff on public.job_required_parts
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

-- ── 5) Reload PostgREST schema cache ─────────────────────────────────────
NOTIFY pgrst, 'reload schema';

-- ── 6) Report ────────────────────────────────────────────────────────────
select table_name, is_insertable_into
from information_schema.tables
where table_schema = 'public' and table_name = 'job_required_parts';

select column_name, data_type, is_nullable
from information_schema.columns
where table_schema = 'public' and table_name = 'transaction_products'
order by ordinal_position;