-- ════════════════════════════════════════════════════════════════════════
-- 20260901_messenger_presence.sql
-- Staff messenger (1-on-1) + online presence.
--
-- New features:
--   1) `messages`      — user-to-user direct messages (staff/admin/developer).
--   2) `user_presence` — per-user online/offline + last_seen (realtime).
--
-- Security posture (RLS lockdown ke pattern pe):
--   • `is_frontend_staff()` = helper (admin/staff/developer) functions jo
--     20260911 lockdown me bani hain — yahan reuse.
--   • messages: staff sab select kar sakta hai jab wo sender YA recipient ho;
--     insert bhi sirf us conversation ka member → koi uski jhol nahi kar sakta.
--   • user_presence: staff sabke presence rows padh sakta hai (status display
--     ke liye); har user SIRF apni row likh/update kar sakta hai (auth.uid()).
--   • messages/user_presence dono Realtime par publish hote hain (live chat
--     + live presence dot). RLS realtime par bhi enforce hota hai (Realtime
--     Authorization = SELECT policy) — isliye messages ke liye recipient/
--     sender policy hi broadcast scope bhi decide karegi.
--
-- FULLY IDEMPOTENT — har create se pehle drop-if-exists.
-- Apply: Supabase SQL Editor (ek baar). Verify: `node scripts/verify-rls.cjs`.
-- ════════════════════════════════════════════════════════════════════════

-- ── 1) user_presence ─────────────────────────────────────────────────────
create table if not exists public.user_presence (
  user_id    uuid primary key references public.profiles (id) on delete cascade,
  status     text not null default 'offline' check (status in ('online', 'offline')),
  last_seen  timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.user_presence enable row level security;

-- Staff sab presence dekh sakta hai (status/last_seen display ke liye).
drop policy if exists msg_presence_staff_select on public.user_presence;
create policy msg_presence_staff_select on public.user_presence
  for select to authenticated
  using (public.is_frontend_staff());

-- Har user apni hi presence row likh/update kar sakta hai.
drop policy if exists msg_presence_self_write on public.user_presence;
create policy msg_presence_self_write on public.user_presence
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid() and public.is_frontend_staff());

create index if not exists user_presence_status_idx on public.user_presence (status);

-- ── 2) messages ──────────────────────────────────────────────────────────
create table if not exists public.messages (
  id           bigint generated by default as identity primary key,
  sender_id    uuid not null references public.profiles (id) on delete cascade,
  recipient_id uuid not null references public.profiles (id) on delete cascade,
  content      text not null check (char_length(btrim(content)) > 0),
  read_at      timestamptz,
  created_at   timestamptz not null default now(),
  constraint messages_no_self check (sender_id <> recipient_id)
);

alter table public.messages enable row level security;

-- Select: user tabhi dekh sakta hai jab wo sender YA recipient ho.
-- (Realtime broadcast bhi isi SELECT policy ke under rehta hai.)
drop policy if exists msg_messages_select on public.messages;
create policy msg_messages_select on public.messages
  for select to authenticated
  using (
    public.is_frontend_staff()
    and (sender_id = auth.uid() or recipient_id = auth.uid())
  );

-- Insert: sirf sender khud + staff — koi aur ki taraf se message forge nahi.
drop policy if exists msg_messages_insert on public.messages;
create policy msg_messages_insert on public.messages
  for insert to authenticated
  with check (
    public.is_frontend_staff()
    and sender_id = auth.uid()
  );

-- Update: sirf read_at mark (recipient apne messages read kar sakta hai).
drop policy if exists msg_messages_update on public.messages;
create policy msg_messages_update on public.messages
  for update to authenticated
  using (recipient_id = auth.uid() and public.is_frontend_staff())
  with check (
    recipient_id = auth.uid()
    and public.is_frontend_staff()
    and sender_id = auth.uid()
  );

create index if not exists messages_conv_idx
  on public.messages (sender_id, recipient_id, created_at);
create index if not exists messages_recipient_unread_idx
  on public.messages (recipient_id, read_at);

-- ── 3) Realtime ──────────────────────────────────────────────────────────
-- (client code in tables ke changes subscribe karta hai; dashboard me bhi
--  in tables par Replication ON kar sakte ho. Ye `alter publication`
--  idempotent-safe hai.)
do $$
begin
  alter publication supabase_realtime add table public.messages;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.user_presence;
exception when duplicate_object then null;
end $$;

-- ── 4) Report ───────────────────────────────────────────────────────────
select relname as table, relrowsecurity as rls_enabled
from pg_class
where relnamespace = 'public'::regnamespace
  and relname in ('messages', 'user_presence')
order by relname;
