-- ============================================================================
-- 20260816_inventory_purchase_orders.sql
-- Inventory "krantikari" phase ke liye 2 naye table sets:
--
--   1) Purchase Order workflow
--        - purchase_orders       : ek PO header (supplier, status, total, dates)
--        - purchase_order_items  : PO ke andar products (qty ordered/received)
--      Status flow: pending -> ordered -> received (cancel bhi allowed).
--      Jab PO "received" mark ho to inventory_list me stock-in entries banti hain
--      (frontend isse handle karega; is file me sirf schema hai).
--
--   2) PWA push notification subscriptions
--        - push_subscriptions    : har user ke browser push subscription ki keys
--      In-app low-stock alerts pehle se hain (AIAlertsWidget); ye table PWA
--      web-push deliver karne ke liye subscription store karta hai.
--
-- Style: project ke existing tables jaisa (bigint identity, date_created/
-- date_updated default now(), RLS + "Allow authenticated access" policy).
-- Idempotent: baar baar run karne se error nahi aayega.
--
-- Apply: Supabase SQL Editor me run karo (ek baar).
-- ============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- 1) PURCHASE ORDERS
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.purchase_orders (
  id             bigint generated by default as identity primary key,
  po_code        text not null unique,
  supplier_id    bigint,
  status         text not null default 'pending'
                 check (status in ('pending', 'ordered', 'received', 'cancelled')),
  expected_date  date,
  notes          text default '',
  total_amount   numeric(12,2) not null default 0,
  received_date  date,
  date_created   timestamp with time zone default now() not null,
  date_updated   timestamp with time zone default now() not null
);

alter table public.purchase_orders
  drop constraint if exists purchase_orders_supplier_fk;
alter table public.purchase_orders
  add constraint purchase_orders_supplier_fk
  foreign key (supplier_id) references public.suppliers (id)
  on delete set null;

create index if not exists purchase_orders_status_idx
  on public.purchase_orders (status);
create index if not exists purchase_orders_supplier_idx
  on public.purchase_orders (supplier_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2) PURCHASE ORDER ITEMS
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.purchase_order_items (
  id                 bigint generated by default as identity primary key,
  purchase_order_id  bigint not null,
  product_id         bigint not null,
  qty_ordered        integer not null default 0,
  qty_received       integer not null default 0,
  unit_cost          numeric(12,2) not null default 0,
  date_created       timestamp with time zone default now() not null
);

alter table public.purchase_order_items
  drop constraint if exists purchase_order_items_po_fk;
alter table public.purchase_order_items
  add constraint purchase_order_items_po_fk
  foreign key (purchase_order_id) references public.purchase_orders (id)
  on delete cascade;

alter table public.purchase_order_items
  drop constraint if exists purchase_order_items_product_fk;
alter table public.purchase_order_items
  add constraint purchase_order_items_product_fk
  foreign key (product_id) references public.product_list (id)
  on delete restrict;

create index if not exists purchase_order_items_po_idx
  on public.purchase_order_items (purchase_order_id);
create index if not exists purchase_order_items_product_idx
  on public.purchase_order_items (product_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3) PWA PUSH SUBSCRIPTIONS
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.push_subscriptions (
  id             bigint generated by default as identity primary key,
  user_id        uuid,
  endpoint       text not null unique,
  p256dh         text not null default '',
  auth           text not null default '',
  device_name    text default '',
  enabled        boolean not null default true,
  date_created   timestamp with time zone default now() not null,
  date_updated   timestamp with time zone default now() not null
);

alter table public.push_subscriptions
  drop constraint if exists push_subscriptions_user_fk;
alter table public.push_subscriptions
  add constraint push_subscriptions_user_fk
  foreign key (user_id) references public.profiles (id)
  on delete cascade;

create index if not exists push_subscriptions_user_idx
  on public.push_subscriptions (user_id);
create index if not exists push_subscriptions_enabled_idx
  on public.push_subscriptions (enabled);

-- ─────────────────────────────────────────────────────────────────────────────
-- RLS: authenticated role ko sab allow (project convention — single-owner app)
-- ─────────────────────────────────────────────────────────────────────────────
alter table public.purchase_orders       enable row level security;
alter table public.purchase_order_items   enable row level security;
alter table public.push_subscriptions     enable row level security;

drop policy if exists "Allow authenticated access" on public.purchase_orders;
create policy "Allow authenticated access"
  on public.purchase_orders
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Allow authenticated access" on public.purchase_order_items;
create policy "Allow authenticated access"
  on public.purchase_order_items
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Allow authenticated access" on public.push_subscriptions;
create policy "Allow authenticated access"
  on public.push_subscriptions
  to authenticated
  using (true)
  with check (true);

-- ─────────────────────────────────────────────────────────────────────────────
-- Auto-update date_updated on UPDATE (convention: transaction_list-style)
-- ─────────────────────────────────────────────────────────────────────────────
create or replace function public.touch_purchase_orders()
returns trigger language plpgsql as $$
begin
  new.date_updated = now();
  return new;
end;
$$;

drop trigger if exists purchase_orders_touch on public.purchase_orders;
create trigger purchase_orders_touch
  before update on public.purchase_orders
  for each row execute function public.touch_purchase_orders();

create or replace function public.touch_push_subscriptions()
returns trigger language plpgsql as $$
begin
  new.date_updated = now();
  return new;
end;
$$;

drop trigger if exists push_subscriptions_touch on public.push_subscriptions;
create trigger push_subscriptions_touch
  before update on public.push_subscriptions
  for each row execute function public.touch_push_subscriptions();
