-- 20260917_supplier_visiting_card.sql
-- Supplier visiting card + multiple contact numbers + WhatsApp usable contacts.
--
-- 1) suppliers.photo_url  — visiting card image public URL (txt, empty default).
-- 2) supplier_contacts    — naye table: har supplier ke multiple contact numbers,
--    label (Mobile/Office/WhatsApp/custom) + is_primary flag.
-- 3) supplier-photos      — storage bucket (same idempotent pattern as others).
-- 4) Seed: existing suppliers.contact ko pehla supplier_contacts row banake
--    is_primary=true set karta hai (NOT EXISTS guard → re-run safe).
--
-- Backward compat: suppliers.contact ab PRIMARY contact number rakhta hai
-- (frontend har save par usi se sync karta hai), taaki sara legacy code
-- (wa.me links, JobRequiredParts, reports, POs) bina change chalta rahe.

-- ── 1) suppliers.photo_url ───────────────────────────────────────────────────
ALTER TABLE public.suppliers ADD COLUMN IF NOT EXISTS photo_url TEXT DEFAULT '';

-- ── 2) supplier_contacts table ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.supplier_contacts (
    id bigint NOT NULL,
    supplier_id bigint NOT NULL,
    label text DEFAULT ''::text NOT NULL,
    phone text DEFAULT ''::text NOT NULL,
    is_primary boolean DEFAULT false NOT NULL,
    date_created timestamp with time zone DEFAULT now() NOT NULL
);

do $$ begin if not exists (select 1 from pg_attribute a where a.attrelid='public.supplier_contacts'::regclass and a.attname='id' and a.attidentity<>'') then
  alter table public.supplier_contacts alter column id add generated by default as identity (SEQUENCE NAME public.supplier_contacts_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);
end if; end $$;

do $$ begin if not exists (select 1 from pg_constraint where conname='supplier_contacts_pkey' and conrelid='public.supplier_contacts'::regclass) then
  alter table only public.supplier_contacts add constraint supplier_contacts_pkey primary key (id);
end if; end $$;

do $$ begin if not exists (select 1 from pg_constraint where conname='supplier_contacts_supplier_fk' and conrelid='public.supplier_contacts'::regclass) then
  alter table only public.supplier_contacts add constraint supplier_contacts_supplier_fk foreign key (supplier_id) references public.suppliers(id) on delete cascade;
end if; end $$;

CREATE INDEX IF NOT EXISTS idx_supplier_contacts_supplier_id ON public.supplier_contacts USING btree (supplier_id);

-- ── 3) supplier-photos bucket ────────────────────────────────────────────────
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('supplier-photos', 'supplier-photos', true, 1048576, array['image/jpeg','image/png','image/webp'])
on conflict (id) do nothing;

DROP POLICY IF EXISTS supplier_photos_staff_insert ON storage.objects;
CREATE POLICY supplier_photos_staff_insert ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'supplier-photos' AND public.is_frontend_staff());
DROP POLICY IF EXISTS supplier_photos_staff_delete ON storage.objects;
CREATE POLICY supplier_photos_staff_delete ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'supplier-photos' AND public.is_frontend_staff());

-- ── 4) Seed legacy single contact ────────────────────────────────────────────
INSERT INTO public.supplier_contacts (supplier_id, label, phone, is_primary)
SELECT s.id, 'Mobile', s.contact, true
  FROM public.suppliers s
 WHERE btrim(s.contact) <> ''
   AND NOT EXISTS (SELECT 1 FROM public.supplier_contacts sc WHERE sc.supplier_id = s.id);

-- ── RLS + grants ─────────────────────────────────────────────────────────────
ALTER TABLE public.supplier_contacts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS rlslock_supplier_contacts_staff ON public.supplier_contacts;
CREATE POLICY rlslock_supplier_contacts_staff ON public.supplier_contacts
  FOR ALL TO authenticated
  USING (public.is_frontend_staff())
  WITH CHECK (public.is_frontend_staff());

GRANT ALL ON TABLE public.supplier_contacts TO anon;
GRANT ALL ON TABLE public.supplier_contacts TO authenticated;
GRANT ALL ON TABLE public.supplier_contacts TO service_role;
GRANT ALL ON SEQUENCE public.supplier_contacts_id_seq TO anon;
GRANT ALL ON SEQUENCE public.supplier_contacts_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.supplier_contacts_id_seq TO service_role;