-- ════════════════════════════════════════════════════════════════════════
-- 20260921_client_contacts.sql
-- Client MULTI-CONTACT model (CLIENTS contact persons = flat, supplier model
-- ke persons+phones mirror nahi — ek client ek PERSON hai; contacts = uske
-- family/relative/dost ke numbers). contract:
--
--  `client_contacts` — client_list ke 1+ mobile numbers, har ek par:
--    • name        — kis ka number hai (rishta: "Pappa", "Bhai", "Beti", ...)
--    • label       — number ka type: Mobile / Office / WhatsApp / Shop / Other
--    • phone       — 10-digit (digits)
--    • is_primary  — ek primary per client (partial unique index enforce)
--
-- `client_list.contact` (legacy flat primary) REPLACE NAHI hota — hamare
-- primary row se sync hota hai; back-compat ke liye rehta hai.
--
-- Follows docs/DATA_MIGRATION_NOTES.md + repo RLS pattern:
--   • bigint identity PK, FK cascade (owned-by)
--   • RLS: `rlslock_*_staff` (is_frontend_staff() gate)
--   • grants anon/authenticated/service_role + sequence grants
--   • touch trigger (date_updated)
--   • idempotent: baar baar run safe
--
-- Apply: Supabase SQL Editor me run karo (ek baar). Verify:
--   select relname from pg_class
--   where relnamespace='public'::regnamespace and relname='client_contacts';
-- ════════════════════════════════════════════════════════════════════════

-- ── 1) client_contacts ───────────────────────────────────────────────────
create table if not exists public.client_contacts (
  id            bigint generated by default as identity,
  client_id     integer not null,
  name          text,
  label         text not null default 'Mobile',
  phone         text not null,
  is_primary    boolean not null default false,
  date_created  timestamptz not null default now(),
  date_updated  timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'client_contacts_pkey'
      and conrelid = 'public.client_contacts'::regclass
  ) then
    alter table only public.client_contacts
      add constraint client_contacts_pkey primary key (id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'client_contacts_client_fk'
      and conrelid = 'public.client_contacts'::regclass
  ) then
    alter table only public.client_contacts
      add constraint client_contacts_client_fk
      foreign key (client_id) references public.client_list(id)
      on delete cascade;
  end if;
end $$;

create index if not exists client_contacts_client_idx
  on public.client_contacts(client_id);

create unique index if not exists client_contacts_phone_uidx
  on public.client_contacts(client_id, lower(trim(phone)));

-- ek client ka ek hi primary number (form self-heal ke liye bhi)
create unique index if not exists client_contacts_primary_uidx
  on public.client_contacts(client_id) where is_primary;

-- ── 2) touch trigger — client_contacts.date_updated ──────────────────────
create or replace function public.touch_client_contacts()
returns trigger language plpgsql as $$
begin
  new.date_updated = now();
  return new;
end;
$$;

drop trigger if exists client_contacts_touch on public.client_contacts;
create trigger client_contacts_touch
  before update on public.client_contacts
  for each row execute function public.touch_client_contacts();

-- ── 3) RLS — is_frontend_staff() gate (repo pattern) ─────────────────────
alter table public.client_contacts enable row level security;

drop policy if exists rlslock_client_contacts_staff on public.client_contacts;
create policy rlslock_client_contacts_staff on public.client_contacts
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

grant all on table public.client_contacts to anon;
grant all on table public.client_contacts to authenticated;
grant all on table public.client_contacts to service_role;
grant usage on sequence public.client_contacts_id_seq to anon, authenticated, service_role;

-- ── 4) Reload PostgREST schema cache ─────────────────────────────────────
NOTIFY pgrst, 'reload schema';

-- ── 5) Report ────────────────────────────────────────────────────────────
select table_name, column_name, data_type, is_nullable
from information_schema.columns
where table_schema = 'public'
  and table_name = 'client_contacts'
order by ordinal_position;