-- ════════════════════════════════════════════════════════════════════════
-- 20260918_supplier_contact_persons.sql
-- Supplier contact PERSONS model (ek firm + 4 contact persons, ek person
-- ke 1+ mobiles, har deal ka apna person).
--
--  1. `supplier_contact_persons` — firm ke andar alag-alag contact person
--     (name, role/designation, notes, is_primary = main deal person).
--  2. `supplier_contact_phones`  — har person ke 1+ phone (label + is_primary
--     per phone). Purane `supplier_contacts` (flat phone rows) ko replace karta
--     hai; table ko DROP NAHI karte — legacy back-compat ke liye rehta hai.
--  3. `purchase_orders.contact_person_id`  — kaunsa PO kis person se deal thi.
--  4. `supplier_payments.contact_person_id` — payment kis person ko diya.
--
-- Follows docs/DATA_MIGRATION_NOTES.md + repo RLS pattern:
--   • bigint identity PK, FK cascade (owned-by) / on delete set null (PO/pay)
--   • RLS: `rlslock_*_staff` (is_frontend_staff() gate)
--   • grants anon/authenticated/service_role + sequence grants
--   • touch trigger (date_updated) persons table par
--   • idempotent: baar baar run safe
--
-- Apply: Supabase SQL Editor me run karo (ek baar). Verify:
--   select relname from pg_class where relnamespace='public'::regnamespace
--     and relname in ('supplier_contact_persons','supplier_contact_phones');
-- ════════════════════════════════════════════════════════════════════════

-- ── 1) supplier_contact_persons ──────────────────────────────────────────
create table if not exists public.supplier_contact_persons (
  id            bigint generated by default as identity,
  supplier_id   bigint not null,
  name          text not null,
  role          text,
  notes         text,
  is_primary    boolean not null default false,
  date_created  timestamptz not null default now(),
  date_updated  timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'supplier_contact_persons_pkey'
      and conrelid = 'public.supplier_contact_persons'::regclass
  ) then
    alter table only public.supplier_contact_persons
      add constraint supplier_contact_persons_pkey primary key (id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'supplier_contact_persons_supplier_fk'
      and conrelid = 'public.supplier_contact_persons'::regclass
  ) then
    alter table only public.supplier_contact_persons
      add constraint supplier_contact_persons_supplier_fk
      foreign key (supplier_id) references public.suppliers(id)
      on delete cascade;
  end if;
end $$;

create index if not exists supplier_contact_persons_supplier_idx
  on public.supplier_contact_persons(supplier_id);

create unique index if not exists supplier_contact_persons_name_uidx
  on public.supplier_contact_persons(supplier_id, lower(trim(name)));

-- ── 2) supplier_contact_phones ───────────────────────────────────────────
create table if not exists public.supplier_contact_phones (
  id            bigint generated by default as identity,
  person_id     bigint not null,
  phone         text not null,
  label         text not null default 'Mobile',
  is_primary    boolean not null default false,
  date_created  timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'supplier_contact_phones_pkey'
      and conrelid = 'public.supplier_contact_phones'::regclass
  ) then
    alter table only public.supplier_contact_phones
      add constraint supplier_contact_phones_pkey primary key (id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'supplier_contact_phones_person_fk'
      and conrelid = 'public.supplier_contact_phones'::regclass
  ) then
    alter table only public.supplier_contact_phones
      add constraint supplier_contact_phones_person_fk
      foreign key (person_id) references public.supplier_contact_persons(id)
      on delete cascade;
  end if;
end $$;

create index if not exists supplier_contact_phones_person_idx
  on public.supplier_contact_phones(person_id);

create unique index if not exists supplier_contact_phones_phone_uidx
  on public.supplier_contact_phones(person_id, lower(trim(phone)));

-- ── 3) purchase_orders.contact_person_id ─────────────────────────────────
alter table public.purchase_orders
  add column if not exists contact_person_id bigint;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'purchase_orders_contact_person_fk'
      and conrelid = 'public.purchase_orders'::regclass
  ) then
    alter table only public.purchase_orders
      add constraint purchase_orders_contact_person_fk
      foreign key (contact_person_id)
      references public.supplier_contact_persons(id)
      on delete set null;
  end if;
end $$;

create index if not exists purchase_orders_contact_person_idx
  on public.purchase_orders(contact_person_id);

-- ── 4) supplier_payments.contact_person_id ───────────────────────────────
alter table public.supplier_payments
  add column if not exists contact_person_id bigint;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'supplier_payments_contact_person_fk'
      and conrelid = 'public.supplier_payments'::regclass
  ) then
    alter table only public.supplier_payments
      add constraint supplier_payments_contact_person_fk
      foreign key (contact_person_id)
      references public.supplier_contact_persons(id)
      on delete set null;
  end if;
end $$;

create index if not exists supplier_payments_contact_person_idx
  on public.supplier_payments(contact_person_id);

-- ── 5) touch trigger — supplier_contact_persons.date_updated ─────────────
create or replace function public.touch_supplier_contact_persons()
returns trigger language plpgsql as $$
begin
  new.date_updated = now();
  return new;
end;
$$;

drop trigger if exists supplier_contact_persons_touch on public.supplier_contact_persons;
create trigger supplier_contact_persons_touch
  before update on public.supplier_contact_persons
  for each row execute function public.touch_supplier_contact_persons();

-- ── 6) RLS — is_frontend_staff() gate (repo pattern) ─────────────────────
alter table public.supplier_contact_persons enable row level security;
alter table public.supplier_contact_phones   enable row level security;

drop policy if exists rlslock_supplier_contact_persons_staff on public.supplier_contact_persons;
create policy rlslock_supplier_contact_persons_staff on public.supplier_contact_persons
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

drop policy if exists rlslock_supplier_contact_phones_staff on public.supplier_contact_phones;
create policy rlslock_supplier_contact_phones_staff on public.supplier_contact_phones
  for all to authenticated
  using (public.is_frontend_staff())
  with check (public.is_frontend_staff());

grant all on table public.supplier_contact_persons to anon;
grant all on table public.supplier_contact_persons to authenticated;
grant all on table public.supplier_contact_persons to service_role;
grant usage on sequence public.supplier_contact_persons_id_seq to anon, authenticated, service_role;

grant all on table public.supplier_contact_phones to anon;
grant all on table public.supplier_contact_phones to authenticated;
grant all on table public.supplier_contact_phones to service_role;
grant usage on sequence public.supplier_contact_phones_id_seq to anon, authenticated, service_role;

-- ── 7) Reload PostgREST schema cache ─────────────────────────────────────
NOTIFY pgrst, 'reload schema';

-- ── 8) Report ────────────────────────────────────────────────────────────
select table_name, column_name, data_type, is_nullable
from information_schema.columns
where table_schema = 'public'
  and table_name in ('supplier_contact_persons', 'supplier_contact_phones',
                     'purchase_orders', 'supplier_payments')
  and (table_name in ('supplier_contact_persons', 'supplier_contact_phones')
       or column_name = 'contact_person_id')
order by table_name, ordinal_position;